### ISSUE TITLE
App dies when backup-manager runs

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#103]
A couple users did report this, but I had the pleasure of encountering this error first hand and the resulting logs pointed in the direction of [developer.android/guide/testing-backup](https://developer.android.com/guide/topics/data/testingbackup).

The backup-manager actions result in the app process getting the cull (?)

```
09-28 18:38:03.901  1266 11045 I PFTBT   : Initiating full-data transport backup of com.celzero.bravedns token: 1847573056
09-28 18:38:03.944  1266  1266 W JobScheduler.Connectivity: Estimated 10314174 bytes over 84 kbps network would take 959279ms; that's insane!
09-28 18:38:04.051  1266 11045 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
09-28 18:38:04.053  1266 11047 D BackupManagerService: awaiting agent for ApplicationInfo{676755a com.celzero.bravedns}
09-28 18:38:04.055  1266  3866 D BackupManagerService: agentConnected pkg=com.celzero.bravedns agent=android.os.BinderProxy@5cd938b
09-28 18:38:04.055  1266 11047 I BackupManagerService: got agent android.app.IBackupAgent$Stub$Proxy@3fe5c68
09-28 18:38:04.055  1266 11047 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
09-28 18:38:04.095  1266 11045 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
09-28 18:38:04.100  1266 11048 I BackupRestoreController: Getting widget state for user: 0
09-28 18:38:04.100  1266 11048 D BackupManagerService: Calling doFullBackup() on com.celzero.bravedns
09-28 18:38:04.100  1266 11048 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
09-28 18:38:04.357  1266 11045 V BackupAgentTimeout: getFullBackupAgentTimeoutMillis(): 300000
09-28 18:38:04.387   727  1374 D NetlinkEvent: Unknown ifindex 201 in RTM_DELADDR
09-28 18:38:04.388   727  1374 D NetlinkEvent: Unknown ifindex 201 in RTM_DELADDR
09-28 18:38:04.395  1266 11045 E PFTBT   : Error -1002 backing up com.celzero.bravedns
09-28 18:38:04.397  1266 11045 I PFTBT   : Transport suggested backoff=807135   
09-28 18:38:04.397  1266 11045 I PFTBT   : Transport rejected backup of com.celzero.bravedns, skipping
09-28 18:38:04.397  1266 11045 W ActivityManager: Unbinding backup agent with no active backup
09-28 18:38:04.403  1266 11045 I PFTBT   : Unbinding agent in com.celzero.bravedns
09-28 18:38:04.403  1266 11045 I PFTBT   : Full backup completed with status: 0 
09-28 18:38:04.413  1266 11045 I PFTBT   : Full data backup pass finished.      
09-28 18:38:04.422  1266  1391 W ActivityManager: Exception when unbinding service com.celzero.bravedns/.service.BraveVPNService
09-28 18:38:04.422  1266  1391 W ActivityManager: android.os.DeadObjectException
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.BinderProxy.transactNative(Native Method)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.BinderProxy.transact(BinderProxy.java:557)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1672)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3619)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:2213)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:15274)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.app.ContextImpl.unbindService(ContextImpl.java:1813)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.app.ContextImpl.unbindService(ContextImpl.java:1813)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.connectivity.Vpn$2.interfaceRemoved(Vpn.java:1472)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.NetworkManagementService.lambda$notifyInterfaceRemoved$3(NetworkManagementService.java:397)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.-$$Lambda$NetworkManagementService$FsR_UD5xfj4hgrwGdX74wq881Bk.sendCallback(Unknown Source:2)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.NetworkManagementService.invokeForAllObservers(NetworkManagementService.java:358)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.NetworkManagementService.notifyInterfaceRemoved(NetworkManagementService.java:397)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.NetworkManagementService.access$600(NetworkManagementService.java:122)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.NetworkManagementService$NetdUnsolicitedEventListener.lambda$onInterfaceRemoved$6$NetworkManagementService$NetdUnsolicitedEventListener(NetworkManagementService.java:745)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.-$$Lambda$NetworkManagementService$NetdUnsolicitedEventListener$h2iz-IbnHpQ97mlJ7G62W2mmanw.run(Unknown Source:4)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.Handler.handleCallback(Handler.java:883)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.Handler.dispatchMessage(Handler.java:100)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.Looper.loop(Looper.java:214)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at android.os.HandlerThread.run(HandlerThread.java:67)
09-28 18:38:04.422  1266  1391 W ActivityManager:   at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by ignoramous** [comment]
Yeah, [so it is expected, I guess, the app being backed-up will be killed](https://stackoverflow.com/questions/33743941/how-do-you-test-the-android-6-0-full-backup-behavior)... we should probably see if there's a way to excuse the app from the backup process.

**Comment by hussainmohd-a** [comment]
Application backup has been disabled for now, android:allowBackup="false". Need  to check for the other possible ways.

**Comment by hussainmohd-a** [comment]
Closing the issue. More on #165

**Comment by ignoramous** [comment]
`android:allowBackup` was re-enabled again which might be causing "migration errors" in the field.
