### ISSUE TITLE
v055a: mutex is already locked by updateTun

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1030]
BraveVPNService.updateTun:2605

```
08-31 13:21:57.495   379 24726 E AndroidRuntime: Process: com.celzero.bravedns, PID: 379
08-31 13:21:57.495   379 24726 E AndroidRuntime: java.lang.IllegalStateException: This mutex is already locked by the specified owner: updateTun
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.sync.MutexImpl.tryLock(Mutex.kt:183)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.sync.MutexImpl.lock$suspendImpl(Mutex.kt:171)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.sync.MutexImpl.lock(Unknown Source:0)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService.updateTun(BraveVPNService.kt:2605)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService.access$updateTun(BraveVPNService.kt:91)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$6.invokeSuspend(BraveVPNService.kt:1392)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$6.invoke(Unknown Source:8)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService$onSharedPreferenceChanged$6.invoke(Unknown Source:2)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at com.celzero.bravedns.service.BraveVPNService$io$1.invokeSuspend(BraveVPNService.kt:2094)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-31 13:21:57.495   379 24726 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(dnsChange), StandaloneCoroutine{Cancelling}@f8b5b20, Dispatchers.IO]
08-31 13:21:57.503  1712  4396 W ActivityTaskManager:   Force finishing activity com.celzero.bravedns/.ui.ConfigureRethinkBasicActivity

```

**Comment by hussainmohd-a** [comment]
The issue is caused by adding the owner's name to the mutex. To provide a temporary fix, we have removed the owner's name. As part of the permanent solution, we will address the problem of multiple method invocations of `updateTun` and `restartVpn`. One approach is to channelize the restart/updates; in this case, there won't be a need to add a mutex to `vpnAdapter`.

**Comment by ignoramous** [comment]
> I've been experiencing this multiple times a day, where Rethink would just crash in the background randomly.

Curious: What's your build version? This crash is from a build that never was never released to f-droid or play-store.

**Comment by ignoramous** [comment]
> I think this might be related to crashes I experience when switching between different DNS types while WireGuard is active.

There are no crashes in the log you've shared (only some wireguard-related logged exceptions which won't crash the app, but have since been removed to avoid confusion).

**Comment by ignoramous** [comment]
mutex has been removed in `v055f`: https://github.com/celzero/rethink-app/commit/4ac686da409eada4c18c2e6d78d1c973b6d5af67
