### ISSUE TITLE
Crash when switching fragments in v051

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#107]
Crash when switching between the main fragments: Home <-> Setting <-> About

```
--------- beginning of crash                                                    
10-13 07:16:03.672  3221  3221 E AndroidRuntime: FATAL EXCEPTION: main          
10-13 07:16:03.672  3221  3221 E AndroidRuntime: Process: com.celzero.bravedns, PID: 3221
10-13 07:16:03.672  3221  3221 E AndroidRuntime: java.lang.IllegalStateException: Fragment l1{36f49e4} (10b4291e-5a7a-40ae-99e8-8437fb3a280f)} not attached to a context.
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at androidx.fragment.app.Fragment.o0(Unknown Source:17)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at s.a.a.a.q1.onFinish(:4)  
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:107)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-13 07:16:03.672  3221  3221 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by hussainmohd-a** [comment]
Issue while adding fragment to the fragment stack has been fixed.
