### ISSUE TITLE
Stackoverflow in DNS Proxy in v051

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#108]
When I click on DNS Proxy from the dropdown in the DNS screen, it just goes:

```
10-13 08:50:37.369  7918  7918 D OPSystemUIWLBHelper: packageName com.android.vending mCurrentMode 0 isMediaAllowed false
10-13 08:50:37.592 13199 13199 D AndroidRuntime: Shutting down VM               
10-13 08:50:38.145 13199 13199 E AndroidRuntime: FATAL EXCEPTION: main          
10-13 08:50:38.145 13199 13199 E AndroidRuntime: Process: com.celzero.bravedns, PID: 13199
10-13 08:50:38.145 13199 13199 E AndroidRuntime: java.lang.StackOverflowError: stack size 8192KB
10-13 08:50:38.145 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:38.145 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
.......
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by com.oneplus.networkspeed.NetworkSpeedView{ff6acf9 V.E...... ......ID 0,0-55,53} during layout: running second layout pass
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by android.widget.TextView{651b43e V.ED..... ......ID 0,0-45,33 #7f0a0472 app:id/speed_word_up} during layout: running second layout pass
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by android.widget.TextView{ba8d29f V.ED..... ......ID 3,26-41,47 #7f0a0471 app:id/speed_word_down} during layout: running second layout pass
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by com.oneplus.networkspeed.NetworkSpeedView{cccfe7d V.E...... ......ID 0,0-55,53} during layout: running second layout pass
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by android.widget.TextView{defee1e V.ED..... ......ID 0,0-45,33 #7f0a0472 app:id/speed_word_up} during layout: running second layout pass
10-13 08:50:39.540  7918  7918 W View    : requestLayout() improperly called by android.widget.TextView{2e9b6ff V.ED..... ......ID 3,26-41,47 #7f0a0471 app:id/speed_word_down} during layout: running second layout pass
10-13 08:50:39.948 13199 13199 I chatty  : uid=10449(com.celzero.bravedns) identical 10953 lines
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
........
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.h.b.hashCode(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at java.lang.Object.toString(Object.java:291)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at java.lang.String.valueOf(String.java:2924)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at java.lang.StringBuilder.append(StringBuilder.java:132)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at s.a.a.d.o.g(:23)         
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$e.h(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$t.j(:78)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.u0(:22)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.s(:2)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:61)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3333)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2810)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7988)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1154)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:977)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:893)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1139)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:883)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:100)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(:18)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1427)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.ScrollView.onMeasure(ScrollView.java:452)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.measure(View.java:24710)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.v1(:12)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.u0(:22)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.s(:2)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.q(:7)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6290)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-13 08:50:39.948 13199 13199 E AndroidRuntime: >--at android.view.View.layout(View.java:22085)

```

**Comment by hussainmohd-a** [comment]
When selecting the DNSProxy, the value from the database is not correctly fetched which resulted in exception, the changes are made so that the right values are fetched and configured in the tunnel.
