### ISSUE TITLE
Download Manager crash in v051

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#109]
From the Settings screen:

1. Enable on-device blocklists for the first time ever.

2. Click `Proceed` to begin the ~40MB download.

3. Navigate away from the screen once the progress bar appears.

4. Come back to the Settings screen and boom.

```
10-13 09:55:19.538 16513 16513 E AndroidRuntime: FATAL EXCEPTION: main          
10-13 09:55:19.538 16513 16513 E AndroidRuntime: Process: com.celzero.bravedns, PID: 16513
10-13 09:55:19.538 16513 16513 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.celzero.bravedns (has extras) } in s.a.a.a.l1$c@dc5d4a9
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:883)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:100)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: Caused by: g0.n.e: /storage/emulated/0/Android/data/com.celzero.bravedns/files/downloads/rd.txt: The source file doesn't exist.
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at g0.n.d.a(:3)             
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at s.a.a.a.l1$c.onReceive(:9)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
10-13 09:55:19.538 16513 16513 E AndroidRuntime: >--... 8 more            
```

**Comment by hussainmohd-a** [comment]
Now the download of the on-device blocklists are handled. Navigating the screen/closing the application has been handled.
