### ISSUE TITLE
Choosing any app in the Enable SOCKS5 Proxy dialog crashes the app

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#110]
Here:

```
10-13 10:17:42.718 23777 23777 D BraveDNS: Pattern not matching - port- 9080 , 9080
10-13 10:17:42.720 23777 23777 D BraveDNS: Pattern matching 1- org.torproject.android
10-13 10:17:42.723 23777 23777 D AndroidRuntime: Shutting down VM               
10-13 10:17:42.724 23777 23777 E AndroidRuntime: FATAL EXCEPTION: main          
10-13 10:17:42.724 23777 23777 E AndroidRuntime: Process: com.celzero.bravedns, PID: 23777
10-13 10:17:42.724 23777 23777 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String s.a.a.h.z2.f' on a null object reference
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at s.a.a.a.u1.onClick(:1)   
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.view.View.performClick(View.java:7201)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at com.google.android.material.button.MaterialButton.performClick(Unknown Source:3)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.view.View.performClickInternal(View.java:7170)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.view.View.access$3500(View.java:806)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.view.View$PerformClick.run(View.java:27562)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:883)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:100)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-13 10:17:42.724 23777 23777 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
10-13 10:17:36.728  1306  1418 I chatty  : uid=1000(system) android.bg identical 1 line
```

**Comment by hussainmohd-a** [comment]
Null pointer exception while selecting the spinner is fixed.
