### ISSUE TITLE
v055b: ConcurrentModificationException in FirewallManager.getAppInfos

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1164]
```
12-12 05:07:16.756  6092  6673 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
12-12 05:07:16.756  6092  6673 E AndroidRuntime: Process: com.celzero.bravedns, PID: 6092
12-12 05:07:16.756  6092  6673 E AndroidRuntime: java.util.ConcurrentModificationException
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.google.common.collect.CompactHashMap$Itr.checkForConcurrentModification(CompactHashMap.java:670)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.google.common.collect.CompactHashMap$Itr.next(CompactHashMap.java:644)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1181)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at java.util.AbstractCollection.toArray(AbstractCollection.java:146)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.getAppInfos(FirewallManager.kt:523)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.informObservers(FirewallManager.kt:527)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.reloadAppList(FirewallManager.kt:457)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invokeSuspend(FirewallManager.kt:420)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invoke(Unknown Source:8)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invoke(Unknown Source:4)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.loadAppFirewallRules(FirewallManager.kt:420)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invokeSuspend(FirewallManager.kt:229)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invoke(Unknown Source:8)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invoke(Unknown Source:2)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$io$1.invokeSuspend(FirewallManager.kt:565)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12-12 05:07:16.756  6092  6673 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b32ec4, Dispatchers.IO]

```

**Comment by hussainmohd-a** [comment]
The issue occurred during the interim stage of development for version `v055b`. It is no longer happening. We will reopen it if it occurs again.
