### ISSUE TITLE
NoSuchElementException at FirewallManager.loadAppFirewallRules in v055b

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1171]
Happened immediately following a reboot (with *Always-on VPN* enabled) at FirewallManager.loadAppFirewallRules(FirewallManager.kt:420)

```
12-22 15:56:57.995  6155  7267 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
12-22 15:56:57.995  6155  7267 E AndroidRuntime: Process: com.celzero.bravedns, PID: 6155
12-22 15:56:57.995  6155  7267 E AndroidRuntime: java.util.NoSuchElementException
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.google.common.collect.CompactHashSet$1.next(CompactHashSet.java:560)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1190)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at java.util.AbstractCollection.toArray(AbstractCollection.java:146)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.getAppInfos(FirewallManager.kt:523)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.informObservers(FirewallManager.kt:527)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.reloadAppList(FirewallManager.kt:457)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invokeSuspend(FirewallManager.kt:420)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invoke(Unknown Source:8)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$loadAppFirewallRules$2.invoke(Unknown Source:4)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager.loadAppFirewallRules(FirewallManager.kt:420)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invokeSuspend(FirewallManager.kt:229)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invoke(Unknown Source:8)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$1.invoke(Unknown Source:2)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at com.celzero.bravedns.service.FirewallManager$io$1.invokeSuspend(FirewallManager.kt:565)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12-22 15:56:57.995  6155  7267 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7a11ae2, Dispatchers.IO]
```

similar #644

**Comment by ignoramous** [comment]
unreleased, but you can build it from the code (:

**Comment by ignoramous** [comment]
fixed in [`v055b`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5b).
