### ISSUE TITLE
v054b: NPE in ConnTrackerBottomSheet#getB

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1193]
```
01-20 05:37:53.167 15025 15025 E AndroidRuntime: FATAL EXCEPTION: main          
01-20 05:37:53.167 15025 15025 E AndroidRuntime: Process: com.celzero.bravedns, PID: 15025
01-20 05:37:53.167 15025 15025 E AndroidRuntime: java.lang.NullPointerException 
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.celzero.bravedns.ui.bottomsheet.ConnTrackerBottomSheet.getB(ConnTrackerBottomSheet.kt:83)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.celzero.bravedns.ui.bottomsheet.ConnTrackerBottomSheet.updateFirewallRulesUi(ConnTrackerBottomSheet.kt:490)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.celzero.bravedns.ui.bottomsheet.ConnTrackerBottomSheet.showFirewallDialog$lambda$14(ConnTrackerBottomSheet.kt:696)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.celzero.bravedns.ui.bottomsheet.ConnTrackerBottomSheet.$r8$lambda$6TwAdZ_3OESq6CZb8qj3zI7w4xg(Unknown Source:0)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.celzero.bravedns.ui.bottomsheet.ConnTrackerBottomSheet$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:240)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:351)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8377)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
01-20 05:37:53.167 15025 15025 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

**Comment by hussainmohd-a** [comment]
Fixed https://github.com/hussainmohd-a/rethink-app/commit/754c12188fd0bd5ef60e81adda4e1efee9f6eaa6. removed confirmation dialog from bottom sheet for multiple apps.
