### ISSUE TITLE
v055b: IllegalStateException in HomeScreenFragment$observeLogsCount view-data binding

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1205]
```
01-31 19:12:07.749  4787  4787 E AndroidRuntime: FATAL EXCEPTION: main          
01-31 19:12:07.749  4787  4787 E AndroidRuntime: Process: com.celzero.bravedns, PID: 4787
01-31 19:12:07.749  4787  4787 E AndroidRuntime: java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:63)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:52)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment.getB(HomeScreenFragment.kt:88)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment.access$getB(HomeScreenFragment.kt:87)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment$observeLogsCount$1$1.invokeSuspend(HomeScreenFragment.kt:485)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment$observeLogsCount$1$1.invoke(Unknown Source:8)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment$observeLogsCount$1$1.invoke(Unknown Source:2)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment$uiCtx$2.invokeSuspend(HomeScreenFragment.kt:1107)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:942)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:240)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:351)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8377)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
01-31 19:12:07.749  4787  4787 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b800261, Dispatchers.Main.immediate]

```

**Comment by hussainmohd-a** [comment]
Fix: [3300ab7](https://github.com/hussainmohd-a/rethink-app/commit/3300ab7ce5d7a56294fa58bb257bd090fd9a248f)
