### ISSUE TITLE
Disk I/O error on SQLite

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#121]
Exception while the category block for "System Components" in OnePlus. 

Logs: 
```
10-28 01:25:11.079 18486 18660 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
10-28 01:25:11.079 18486 18660 E AndroidRuntime: Process: com.celzero.bravedns, PID: 18486
10-28 01:25:11.079 18486 18660 E AndroidRuntime: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 266 SQLITE_IOERR_READ)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at com.celzero.bravedns.database.CategoryInfoDAO_Impl.getCategoryDetail(CategoryInfoDAO_Impl.java:436)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at com.celzero.bravedns.database.CategoryInfoRepository.updateBlockedCount(CategoryInfoRepository.kt:83)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at com.celzero.bravedns.adapter.FirewallAppListAdapter$getGroupView$1$2.invokeSuspend(FirewallAppListAdapter.kt:432)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-28 01:25:11.079 18486 18660 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-28 01:25:11.082  1244 18870 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-28 01:25:11.083  1244  8396 W ActivityTaskManager:   Force finishing activity com.celzero.bravedns/.ui.FirewallActivity
10-28 01:25:11.095  1244 18870 W DropBoxManagerService: Dropping: data_app_crash (1803 > 0 bytes)
10-28 01:25:11.100  1244  1416 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-28 01:25:11.101  1244  1416 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-28 01:25:11.162   729  1376 D NetlinkEvent: Unknown ifindex 68 in RTM_DELADDR
10-28 01:25:11.193  1244  1398 W ActivityManager: Exception when unbinding service com.celzero.bravedns/.service.BraveVPNService
10-28 01:25:11.193  1244  1398 W ActivityManager: android.os.DeadObjectException
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.BinderProxy.transact(BinderProxy.java:557)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1672)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3619)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:2213)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:15274)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1813)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.connectivity.Vpn$2.interfaceRemoved(Vpn.java:1472)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.NetworkManagementService.lambda$notifyInterfaceRemoved$3(NetworkManagementService.java:397)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.-$$Lambda$NetworkManagementService$FsR_UD5xfj4hgrwGdX74wq881Bk.sendCallback(Unknown Source:2)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.NetworkManagementService.invokeForAllObservers(NetworkManagementService.java:358)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.NetworkManagementService.notifyInterfaceRemoved(NetworkManagementService.java:397)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.NetworkManagementService.access$600(NetworkManagementService.java:122)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.NetworkManagementService$NetdUnsolicitedEventListener.lambda$onInterfaceRemoved$6$NetworkManagementService$NetdUnsolicitedEventListener(NetworkManagementService.java:745)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.-$$Lambda$NetworkManagementService$NetdUnsolicitedEventListener$h2iz-IbnHpQ97mlJ7G62W2mmanw.run(Unknown Source:4)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.Handler.handleCallback(Handler.java:883)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.Looper.loop(Looper.java:214)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-28 01:25:11.193  1244  1398 W ActivityManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by hussainmohd-a** [comment]
Changes done for https://github.com/celzero/rethink-app/issues/122 will apply to this issue as well. Testing in progress.

**Comment by ignoramous** [comment]
This likely fixed itself.
