### ISSUE TITLE
App crash at DNS activation: NPE in RethinkListFragment#updateMaxSwitchUi

### ISSUE THREAD

**Issue by Plobli** [celzero/rethink-app#1214]
Hi. 

When i try to activate a Rethink DNS filter the app crashed. I use Android 14. 
The crash report ist attached. 

[Error in RethinkDNS 1f45e355224a.txt](https://github.com/celzero/rethink-app/files/14178968/Error.in.RethinkDNS.1f45e355224a.txt)

**Comment by ignoramous** [comment]
Thanks. We'll take a look.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.celzero.bravedns.database.RethinkDnsEndpoint.getUrl()' on a null object reference
	at com.celzero.bravedns.ui.RethinkListFragment$updateMaxSwitchUi$1$1.invokeSuspend(Unknown Source:53)
	at com.celzero.bravedns.ui.RethinkListFragment$updateMaxSwitchUi$1$1.invoke(SourceFile:0)
	at com.celzero.bravedns.ui.RethinkListFragment$updateMaxSwitchUi$1$1.invoke(SourceFile:0)
	at com.celzero.bravedns.ui.RethinkListFragment$ioCtx$2.invokeSuspend(Unknown Source:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5fb3b61, Dispatchers.Main.immediate]
```

**Comment by ignoramous** [comment]
If you are willing, can you please screenshots of the homescreen, logs (network/DNS), apps, and universal domain / IP rules screens?

Looks like the database itself is missing, which is very strange. Is this a fresh install? Did you attempt a restore from a backup? Did you upgrade the app and this happened? Did you update the OS?

**Comment by Plobli** [comment]
I installed the app again and all is good. No problem anymore.

**Comment by hussainmohd-a** [comment]
Closing the issue. Please feel free to reopen if the issue still persists
