### ISSUE TITLE
android.database.CursorWindowAllocationException in v052

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#122]
We also see this a lot in the wild.

```
--------- beginning of crash                                                    
10-28 06:46:25.722 17865 17929 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
10-28 06:46:25.722 17865 17929 E AndroidRuntime: Process: com.celzero.bravedns, PID: 17865
10-28 06:46:25.722 17865 17929 E AndroidRuntime: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.celzero.bravedns/databases/bravedns.db' of size 2097152 due to error -1.
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.CursorWindow.nativeCreate(Native Method)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.CursorWindow.<init>(CursorWindow.java:139)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.CursorWindow.<init>(CursorWindow.java:120)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at com.celzero.bravedns.database.AppInfoDAO_Impl.isRootAvailable(AppInfoDAO_Impl.java:2020)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at com.celzero.bravedns.database.AppInfoRepository.isRootUserAvailable(AppInfoRepository.kt:48)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at com.celzero.bravedns.util.RefreshDatabase.insertRootAndroid(RefreshDatabase.kt:154)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at com.celzero.bravedns.util.RefreshDatabase.access$insertRootAndroid(RefreshDatabase.kt:35)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at com.celzero.bravedns.util.RefreshDatabase$getAppInfo$1.invokeSuspend(RefreshDatabase.kt:74)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-28 06:46:25.722 17865 17929 E AndroidRuntime: >--at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-28 06:46:25.724  1244  4705 W ActivityTaskManager:   Force finishing activity com.celzero.bravedns/.ui.HomeScreenActivity
```

**Comment by hussainmohd-a** [comment]
Changes made while inserting/selecting values from database, The transactions are modified for the connection trackers and various other livedata elements. Testing in progress.
