### ISSUE TITLE
v055c: IllegalStateException in HomeScreenFragment.updateUiWithDnsStates: Fragment's view can't be accessed

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1283]
```
03-14 21:44:09.531  6377  6377 E AndroidRuntime: java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:63)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:52)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment.getB(HomeScreenFragment.kt:91)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment.access$getB(HomeScreenFragment.kt:90)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at com.celzero.bravedns.ui.fragment.HomeScreenFragment$updateUiWithDnsStates$1.invokeSuspend(HomeScreenFragment.kt:543)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:942)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:240)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:351)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8377)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
03-14 21:44:09.531  6377  6377 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(dnsStatusCheck), StandaloneCoroutine{Cancelling}@3b9d79b, Dispatchers.Main]

```

**Comment by hussainmohd-a** [comment]
This issue occurred during the intermediate changes made to update the state of the selected DNS transport in Home screen. It has since been addressed in subsequent changes.
