### ISSUE TITLE
v055c: java.io.FileNotFoundException in BugReportZipper#getZipFile

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1304]
```
03-20 00:08:38.884  8882 10113 E JobScheduler: File not found exception while creating zip file
03-20 00:08:38.884  8882 10113 E JobScheduler: java.io.FileNotFoundException: /data/data/com.celzero.bravedns/files/rethinkdns.bugreport.zip (No such file or directory)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at java.util.zip.ZipFile.open(Native Method)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at java.util.zip.ZipFile.<init>(ZipFile.java:158)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at com.celzero.bravedns.scheduler.BugReportZipper.getZipFile(Unknown Source:9)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at com.celzero.bravedns.scheduler.BugReportZipper.prepare(Unknown Source:50)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at com.celzero.bravedns.scheduler.BugReportCollector.prepare(Unknown Source:15)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at com.celzero.bravedns.scheduler.BugReportCollector.doWork(Unknown Source:33)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(Unknown Source:32)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
03-20 00:08:38.884  8882 10113 E JobScheduler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
03-20 00:08:38.884  8882 10113 I JobScheduler: app-exit-info job path: /data/data/com.celzero.bravedns/files/bugreport/bugreport_0.txt
03-20 00:08:38.884  8882 10113 I JobScheduler: app-exit-info job file: bugreport_0.txt, /data/data/com.celzero.bravedns/files/bugreport/bugreport_0.txt
```

**Comment by hussainmohd-a** [comment]
We can ignore this exception because if there is no zip file, a new zip file will be created. This scenario can occur during the first time setup or when there is no existing zip file. In such cases, a new zip file will be generated. Additionally, the log level has been modified from error to warn. Fix: https://github.com/celzero/rethink-app/pull/1301/commits/a4e008d7fea23cd03c9eb933c93315406ac91d4d
