### ISSUE TITLE
IllegalStateException in SettingsFragment for missing Context

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#132]
```
11-05 10:05:47.151 32760 18020 E AndroidRuntime: Process: com.celzero.bravedns, PID: 32760
11-05 10:05:47.151 32760 18020 E AndroidRuntime: java.lang.IllegalStateException: Fragment SettingsFragment{f7220fe} (ec1c20d8-681f-45a3-b2fb-36853a2a4073)} not attached to a context.
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at com.celzero.bravedns.ui.SettingsFragment$run$1.onResponse(SettingsFragment.kt:490)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-05 10:05:47.151 32760 18020 E AndroidRuntime: >--at java.lang.Thread.run(Thread.java:919)
```

**Comment by hussainmohd-a** [comment]
If the user navigates the page during the server call, the context is returned null from the fragment was causing this issue. The context values are handled differently now in the SettingsFragment which solved this issue.
