### ISSUE TITLE
v055e: IllegalArgumentException: foregroundServiceType 0x00000400 is not a subset of foregroundServiceType attribute 0x40000000 in service element of manifest file

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1374]
> @mad1mystic Hi, if you're technical enough, can you post output from `adb logcat`? We've got Android 14 devices ourselves and do not see any more crashes.
> 
> Here is the log 

```
type: crash
osVersion: Redmi/sweet_eea/sweet:13/RKQ1.210614.002/V14.0.9.0.TKFEUXM:user/release-keys
package: com.celzero.bravedns:36
process: com.celzero.bravedns
processUptime: 384 + 50 ms
installer: com.celzero.bravedns

java.lang.IllegalArgumentException: foregroundServiceType 0x00000400 is not a subset of foregroundServiceType attribute 0x40000000 in service element of manifest file
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
	at android.os.Parcel.createException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:3030)
	at android.os.Parcel.readException(Parcel.java:2972)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6825)
	at android.app.Service.startForeground(Service.java:862)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$$ExternalSyntheticApiModelOutline0.m(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invokeSuspend(Unknown Source:74)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invoke(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invoke(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$ui$1.invokeSuspend(Unknown Source:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8275)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cde266, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2064)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1690)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3418)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2782)
```
>
> Still crashing for me on Android 14

_Originally posted by @mad1mystic in https://github.com/celzero/rethink-app/issues/1339#issuecomment-2041170154_

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/hussainmohd-a/rethink-app/commit/4c846d523a5cbd415144b885027b832e1af536a1
