### ISSUE TITLE
v055e: SIGABRT in wgproxy: channel closed for send

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1395]
A user reports crash from stopping / starting WireGuard repeatedly.

```
04-26 09:23:48.284 10973     0 E Go      : panic: send on closed channel
04-26 09:23:48.284 10973     0 E Go      : 
04-26 09:23:48.284 10973     0 E Go      : goroutine 1123 [running]:
04-26 09:23:48.284 10973     0 E Go      : github.com/celzero/firestack/intra/ipn.(*wgtun).WriteNotify(0x40000a8820)
04-26 09:23:48.284 10973     0 E Go      : 	/home/jitpack/build/intra/ipn/wgproxy.go:625 +0x1bc
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/link/channel.(*queue).Write(0x400023a500, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/link/channel/channel.go:100 +0x164
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).WritePackets(0x4000200f60, {{0x4000360130, 0x1, 0x1}})
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/link/channel/channel.go:258 +0x6c
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*delegatingQueueingDiscipline).WritePacket(0x40001b21e0, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/stack/nic.go:146 +0xa4
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writeRawPacket(0x40003ae008, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/stack/nic.go:399 +0x3c
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writePacket(0x40003ae008, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/stack/nic.go:386 +0x40
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).WritePacket(0x40003ae008, 0x40003446c0, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/stack/nic.go:347 +0x124
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).writePacketPostRouting(0x4000357b08, 0x40003446c0, 0x4000418000, 0x0?)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/network/ipv4/ipv4.go:598 +0x418
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).writePacket(0x4000357b08, 0x40003446c0, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/network/ipv4/ipv4.go:548 +0x17c
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).WritePacket(0x4000357b08, 0x40003446c0, {0x800?, 0x0?, 0x0?}, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/network/ipv4/ipv4.go:516 +0x9c
04-26 09:23:48.285 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0x40003446c0, {0x6c8c80a?, 0x0?, 0x0?}, 0x4000418000)
04-26 09:23:48.285 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/stack/route.go:500 +0x78
04-26 09:23:48.285  2337 11435 V NativeCrypto: SSL shutdown failed: ssl=0xb4000075c22c5d48: I/O error during system call, Broken pipe
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.sendTCP(0x40003446c0, {{0x4a98, {{0xa, 0xc8, 0xc8, 0x6, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...}, ...)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/connect.go:916 +0x1b8
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendTCP(0x400044d808, 0x7545b2ea94?, {{0x4a98, {{0xa, 0xc8, 0xc8, 0x6, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...}, ...)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/connect.go:814 +0x90
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendRaw(0x400044d808, 0x4000418000, 0x11, 0x507df71f, 0x5fc06952, 0x1000)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/connect.go:983 +0x24c
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegmentFromPacketBuffer(0x40002d0008, 0x4000685180, 0x11, 0x507df71f)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/snd.go:1687 +0xdc
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegment(0x40002d0008, 0x4000298900)
04-26 09:23:48.286  2337 11435 E WakeLock: GCM_HB_ALARM release without a matched acquire!
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/snd.go:1648 +0x1a0
04-26 09:23:48.286  2337 11435 W WakeLock: GCM_HB_ALARM counter does not exist
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).maybeSendSegment(0x40002d0008, 0x4000298900, 0x400014de28?, 0x45e73134?)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/snd.go:878 +0x1f4
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendData(0x40002d0008)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/snd.go:982 +0x1d0
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendData(0x400044d808?, 0x6c8c80a?)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/connect.go:1007 +0x40
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).shutdownLocked(0x400044d808, 0x8?)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/endpoint.go:2550 +0x490
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).closeLocked(0x400044d808)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/endpoint.go:1089 +0xa0
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).Close(0x400044d808)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/transport/tcp/endpoint.go:1059 +0x30
04-26 09:23:48.286 10973     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/adapters/gonet.(*TCPConn).Close(0x400013ab80?)
04-26 09:23:48.286 10973     0 E Go      : 	/tmp/gomobile-work-3603758480/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3/pkg/tcpip/adapters/gonet/gonet.go:418 +0x28
04-26 09:23:48.286 10973     0 E Go      : created by github.com/celzero/firestack/intra/core.(*cm).Clear in goroutine 986
04-26 09:23:48.286 10973     0 E Go      : 	/home/jitpack/build/intra/core/connmap.go:227 +0x2fc
```

**Comment by ignoramous** [comment]
Fix (in firestack) will land in `v055i`.
