### ISSUE TITLE
StrictMode: BraveVPNService$logAndToastIfNeeded IncorrectContextUseViolation

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1413]
```
05-01 21:53:07.872  8795  8795 D StrictMode: StrictMode policy violation: android.os.strictmode.IncorrectContextUseViolation: WindowManager should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.os.StrictMode.onIncorrectContextUsed(StrictMode.java:2395)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.app.ContextImpl.getSystemService(ContextImpl.java:2260)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.content.ContextWrapper.getSystemService(ContextWrapper.java:944)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.content.Context.getSystemService(Context.java:4420)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.widget.ToastPresenter.<init>(ToastPresenter.java:105)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.widget.Toast$TN.<init>(Toast.java:648)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.widget.Toast.<init>(Toast.java:175)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.widget.Toast.makeText(Toast.java:504)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.widget.Toast.makeText(Toast.java:493)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.celzero.bravedns.util.Utilities.showToastUiCentered(Utilities.kt:291)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.celzero.bravedns.service.BraveVPNService$logAndToastIfNeeded$2.invokeSuspend(BraveVPNService.kt:1858)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.celzero.bravedns.service.BraveVPNService$logAndToastIfNeeded$2.invoke(Unknown Source:8)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.celzero.bravedns.service.BraveVPNService$logAndToastIfNeeded$2.invoke(Unknown Source:2)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.celzero.bravedns.service.BraveVPNService$uiCtx$2.invokeSuspend(BraveVPNService.kt:2672)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.os.Handler.handleCallback(Handler.java:958)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.os.Handler.dispatchMessage(Handler.java:99)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.os.Looper.loopOnce(Looper.java:257)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.os.Looper.loop(Looper.java:368)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.app.ActivityThread.main(ActivityThread.java:8826)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at java.lang.reflect.Method.invoke(Native Method)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
05-01 21:53:07.872  8795  8795 D StrictMode: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
05-01 21:53:07.872  8795  8795 D StrictMode: Caused by: java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.celzero.bravedns.service.BraveVPNService@d98dad9
05-01 21:53:07.872  8795  8795 D StrictMode: >--at android.app.ContextImpl.getSystemService(ContextImpl.java:2259)
05-01 21:53:07.872  8795  8795 D StrictMode: >--... 22 more    
```

**Comment by hussainmohd-a** [comment]
This issue occurs only in debug mode when we attempt to show a toast message from the VPN service context rather than from a UI-related context. Closing, as this problem does not affect the production environment.
