### ISSUE TITLE
v055i: ANR in NetworkLogsActivity

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1415]
ANR while searching (more than one searches) in *DNS Log* for an IPv6 address (adding / removing chars) and then scrolling, and then navigating using the back key of the softkeybar.

```
05-02 04:47:15.813  1798  2248 I WindowManager: ANR in Window{b823e4d u0 com.celzero.bravedns/com.celzero.bravedns.ui.activity.NetworkLogsActivity}.
Reason:Input dispatching timed out (b823e4d com.celzero.bravedns/com.celzero.bravedns.ui.activity.NetworkLogsActivity (server) is not responding. Waited 5000ms for MotionEvent)
```

```
05-02 04:47:13.789  8795 20446 I Quality : stackInfo :
----- pid 8795 at 2024-05-02 04:47:13.768 -----;
Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=8795;
  at java.util.ArrayList.get(ArrayList.java:434);
  at androidx.recyclerview.widget.AdapterHelper.findPositionOffset(AdapterHelper.java:474);
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:422);
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:3942);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4209);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010);
  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891);
  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880);
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1640);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332);
  at android.widget.FrameLayout.onLayout(FrameLayout.java:270);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878);
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689);
  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124);
  at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969);
  at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071);
```

```
05-02 04:47:16.807  8795 20446 I Quality : stackInfo :
----- pid 8795 at 2024-05-02 04:47:16.792 -----;
Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=8795;
  at java.util.Objects.checkIndex(Objects.java:359);
  at java.util.ArrayList.get(ArrayList.java:434);
  at androidx.recyclerview.widget.AdapterHelper.findPositionOffset(AdapterHelper.java:474);
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:422);
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:3942);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4209);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010);
  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891);
  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880);
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1640);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332);
  at android.widget.FrameLayout.onLayout(FrameLayout.java:270);
  at android.view.View.layout(View.java:24782);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878);
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689);
  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124);
  at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969);
```

```
05-02 04:47:26.573  1798 21681 E ActivityManager: ANR in com.celzero.bravedns   
05-02 04:47:26.573  1798 21681 E ActivityManager: PID: 8795                     
05-02 04:47:26.573  1798 21681 E ActivityManager: Reason: App requested: MainThread worked timeout
05-02 04:47:26.573  1798 21681 E ActivityManager: ErrorId: 65dbfc7b-d871-470d-baff-3e6bf68598b1
05-02 04:47:26.573  1798 21681 E ActivityManager: Frozen: false                 
05-02 04:47:26.573  1798 21681 E ActivityManager: Load: 24.96 / 24.45 / 24.04   
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- Output from /proc/pressure/memory -----
05-02 04:47:26.573  1798 21681 E ActivityManager: some avg10=0.00 avg60=0.00 avg300=0.00 total=1429401053
05-02 04:47:26.573  1798 21681 E ActivityManager: full avg10=0.00 avg60=0.00 avg300=0.00 total=557882885
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- End output from /proc/pressure/memory -----
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- Output from /proc/pressure/cpu -----
05-02 04:47:26.573  1798 21681 E ActivityManager: some avg10=8.74 avg60=6.45 avg300=5.14 total=77766180669
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- End output from /proc/pressure/cpu -----
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- Output from /proc/pressure/io -----
05-02 04:47:26.573  1798 21681 E ActivityManager: some avg10=0.00 avg60=0.00 avg300=0.04 total=2157608776
05-02 04:47:26.573  1798 21681 E ActivityManager: full avg10=0.00 avg60=0.00 avg300=0.02 total=1429615274
05-02 04:47:26.573  1798 21681 E ActivityManager: ----- End output from /proc/pressure/io -----
05-02 04:47:26.573  1798 21681 E ActivityManager:                               
05-02 04:47:26.573  1798 21681 E ActivityManager: CPU usage from 290324ms to -1ms ago (2024-05-02 04:42:33.562 to 2024-05-02 04:47:23.887):
05-02 04:47:26.573  1798 21681 E ActivityManager:   40% 1140/surfaceflinger: 33% user + 7.3% kernel / faults: 24361 minor
05-02 04:47:26.573  1798 21681 E ActivityManager:   34% 8795/com.celzero.bravedns: 28% user + 5.6% kernel / faults: 45788 minor 1982 major
05-02 04:47:26.573  1798 21681 E ActivityManager:   23% 1798/system_server: 14% user + 9.4% kernel / faults: 42777 minor 1 major
05-02 04:47:26.573  1798 21681 E ActivityManager:   17% 980/android.hardware.graphics.composer@2.3-service: 6.4% user + 10% kernel / faults: 249 minor
05-02 04:47:26.573  1798 21681 E ActivityManager:   5.6% 2512/com.android.systemui: 3.9% user + 1.6% kernel / faults: 32486 minor 12 major
05-02 04:47:26.573  1798 21681 E ActivityManager:   2.5% 10617/com.google.android.inputmethod.latin: 1.7% user + 0.7% kernel / faults: 12011 minor 53 major
05-02 04:47:26.573  1798 21681 E ActivityManager:   1.7% 1429/vendor.mediatek.hardware.pq@2.2-service: 1.3% user + 0.4% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   1.6% 2692/com.android.phone: 1% user + 0.6% kernel / faults: 8629 minor
05-02 04:47:26.573  1798 21681 E ActivityManager:   1.5% 421/cmdq_flushq: 0% user + 1.5% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   1% 29562/com.android.chrome: 0.9% user + 0.1% kernel / faults: 4298 minor 3 major
05-02 04:47:26.573  1798 21681 E ActivityManager: 21% TOTAL: 12% user + 6.1% kernel + 0% iowait + 1.8% irq + 0.5% softirq
05-02 04:47:26.573  1798 21681 E ActivityManager: CPU usage from 107ms to 1362ms later (2024-05-02 04:47:23.993 to 2024-05-02 04:47:25.248) with 99% awake:
05-02 04:47:26.573  1798 21681 E ActivityManager:   121% 646/logd: 6% user + 115% kernel / faults: 1617 minor
05-02 04:47:26.573  1798 21681 E ActivityManager:     31% 21721/logd.reader.per: 2.5% user + 29% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     29% 21763/logd.reader.per: 1.7% user + 27% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     23% 21759/logd.reader.per: 1.7% user + 21% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.8% 653/logd.reader: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.8% 654/logd.writer: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   102% 1798/system_server: 46% user + 55% kernel / faults: 23824 minor 238 major
05-02 04:47:26.573  1798 21681 E ActivityManager:     48% 21682/AnrAuxiliaryTas: 12% user + 35% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     43% 1804/Signal Catcher: 22% user + 20% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1813/binder:1798_2: 0.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1845/android.display: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1855/oplus.bg: 0.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 2324/BlobStore: 0.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 4228/nl-oplus_cpu_nl: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 8029/binder:1798_1E: 0.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 21681/AnrConsumer: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   98% 8795/com.celzero.bravedns: 98% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     98% 8795/elzero.bravedns: 98% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   73% 10617/com.google.android.inputmethod.latin: 57% user + 16% kernel / faults: 5434 minor 59 major
05-02 04:47:26.573  1798 21681 E ActivityManager:     71% 10633/Signal Catcher: 53% user + 17% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   8.9% 980/android.hardware.graphics.composer@2.3-service: 8.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     4.4% 1445/OverlayEngine_0: 4.4% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     3.5% 980/composer@2.3-se: 2.6% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.8% 1446/Dispatcher_0: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   8.2% 1140/surfaceflinger: 4.6% user + 3.6% kernel / faults: 1 minor
05-02 04:47:26.573  1798 21681 E ActivityManager:     6.4% 1140/surfaceflinger: 4.6% user + 1.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1237/RenderEngine: 0.9% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1462/TimerDispatch: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   4.8% 173/kswapd0: 0% user + 4.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.7% 1/init: 0% user + 0.7% kernel / faults: 111 minor 3 major
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.7% 17/migration/1: 0% user + 0.7% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.8% 148/ion_history: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.8% 174/kshrink_slabd: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.8% 648/servicemanager: 0.8% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.8% 824/loop32: 0% user + 0.8% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   0.9% 1429/vendor.mediatek.hardware.pq@2.2-service: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:     0.9% 1584/AALMain: 0% user + 0.9% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:   1.8% 11787/com.android.chrome:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:1: 1.8% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:  +0% 21717/sh: 0% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:  +0% 21719/logcat: 0% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:  +0% 21741/logcat: 0% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:  +0% 21752/logcat: 0% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager:  +0% 21787/kworker/u25:5-fsverity_read_queue: 0% user + 0% kernel
05-02 04:47:26.573  1798 21681 E ActivityManager: 78% TOTAL: 34% user + 41% kernel + 0.6% iowait + 1.5% irq + 0.3% softirq
```

**Comment by ignoramous** [comment]
v055o:

```
11-16 18:20:38.655   506 12256 I Quality :+1: 
stackInfo :----- pid 506 at 2024-11-16 18:20:38.645 -----;
Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=506;
  at java.util.ArrayList.get(ArrayList.java:434);
  at androidx.recyclerview.widget.AdapterHelper.findPositionOffset(AdapterHelper.java:474);
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:422);
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:4278);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4545);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346);
  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332);
  at android.widget.FrameLayout.onLayout(FrameLayout.java:270);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407);
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720);
  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425);  at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1145);
  at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2047);
  at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2149);
  at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3867);
  at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:996);
  at android.view.View.dispatchTouchEvent(View.java:15805);
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3167);
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835);
```

**Comment by hussainmohd-a** [comment]
Fixed: 52b9d3f8, 29160784, b2cc8be9
