### ISSUE TITLE
Divide by zero crash when opening stats page

### ISSUE THREAD

**Issue by SkewedZeppelin** [celzero/rethink-app#1458]
```
05-24 11:35:39.598  4550  4605 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
05-24 11:35:39.598  4550  4605 E AndroidRuntime: Process: com.celzero.bravedns, PID: 4550
05-24 11:35:39.598  4550  4605 E AndroidRuntime: java.lang.ArithmeticException: divide by zero
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.calculatePercentage(Unknown Source:4)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.setTotalUsagesUi(Unknown Source:157)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.access$setTotalUsagesUi(Unknown Source:0)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invokeSuspend(Unknown Source:14)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invoke(SourceFile:0)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invoke(SourceFile:0)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$uiCtx$2.invokeSuspend(Unknown Source:30)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
05-24 11:35:39.598  4550  4605 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b40864e, Dispatchers.IO]
```

Introduced in
https://github.com/celzero/rethink-app/commit/d818202cce7b1030e1b664ec975aa31525778fa4#diff-80e8b71942cd7933174b912eb59f477be04a22ff7f52b08388c4afbd7a65af11

https://github.com/celzero/rethink-app/blob/c6638336dd9571613b547aa9cd1e022ac83fb0a4/app/src/full/java/com/celzero/bravedns/ui/fragment/SummaryStatisticsFragment.kt#L164-L167

**Comment by hussainmohd-a** [comment]
Thanks for reporting, this is fixed: https://github.com/celzero/rethink-app/pull/1459/commits/c13f2ab672adef454f16660aa6e820bd10b5fb25, will be part of `v055k`

**Comment by SkewedZeppelin** [comment]
Ah, cool.

I hadn't checked open PRs.
