### ISSUE TITLE
Bug: App crashes when accessing stats page for the first time

### ISSUE THREAD

**Issue by SaadAhmedGit** [celzero/rethink-app#1467]
This happens because of a divide by zero error trying to calculate the percentage of unmetered vs metered bandwidth use but when no bandwidth has been used, the total is zero which when divided by, causes the app to crash.

Here is the output of logcat:

```
java.lang.ArithmeticException: divide by zero
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.calculatePercentage(SummaryStatisticsFragment.kt:175)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.setTotalUsagesUi(SummaryStatisticsFragment.kt:165)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment.access$setTotalUsagesUi(SummaryStatisticsFragment.kt:45)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invokeSuspend(SummaryStatisticsFragment.kt:126)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invoke(Unknown Source:8)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$handleTotalUsagesUi$1$1.invoke(Unknown Source:2)
                                        	at com.celzero.bravedns.ui.fragment.SummaryStatisticsFragment$uiCtx$2.invokeSuspend(SummaryStatisticsFragment.kt:552)
                                        	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                        	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                        	at android.os.Handler.handleCallback(Handler.java:958)
                                        	at android.os.Handler.dispatchMessage(Handler.java:99)
                                        	at android.os.Looper.loopOnce(Looper.java:205)
                                        	at android.os.Looper.loop(Looper.java:294)
                                        	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                        	at java.lang.reflect.Method.invoke(Native Method)
                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                        	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b7cc309, Dispatchers.IO]
```

**Comment by hussainmohd-a** [comment]
Thanks for reporting, this is fixed: https://github.com/celzero/rethink-app/commit/c13f2ab672adef454f16660aa6e820bd10b5fb25, will be part of v055k (released in [website](https://rethinkdns.com/download), [GitHub](https://github.com/celzero/rethink-app/releases/tag/v0.5.5k))

**Comment by SaadAhmedGit** [comment]
Thanks, I can confirm that the fix works. Closing the issue
