### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#1495]
```
Fatal Exception: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.kt:276)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.kt:18)
       at okhttp3.dnsoverhttps.DnsOverHttps$Companion.isPrivateHost$okhttp_dnsoverhttps(DnsOverHttps.kt:11)
       at okhttp3.dnsoverhttps.DnsOverHttps.lookup(DnsOverHttps.kt:15)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:152)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:20)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:17)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:192)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:47)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:31)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:151)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:149)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:151)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:167)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:151)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:151)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:112)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:44)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
    
```

**Comment by hussainmohd-a** [comment]
ref: 
https://medium.com/@wanxiao1994/crash-analysis-unable-to-load-publicsuffixes-gz-resource-from-the-classpath-64k-limit-of-zip-8a41d8e79811

https://programmersought.com/article/25321169177/

https://github.com/square/okhttp/issues/3687

**Comment by hussainmohd-a** [comment]
possible fix: https://github.com/square/okhttp/issues/8154#issuecomment-1868462895

**Comment by hussainmohd-a** [comment]
> possible fix: [square/okhttp#8154 (comment)](https://github.com/square/okhttp/issues/8154#issuecomment-1868462895)

https://square.github.io/okhttp/features/r8_proguard/

**Comment by hussainmohd-a** [comment]
Updated OkHttp to 5.1.0 to fix this issue. Shouldn't see this crash anymore — closing it
