### ISSUE TITLE
Cannot start VPN service with version  v0.5.5m from Fdroid

### ISSUE THREAD

**Issue by timespace314** [celzero/rethink-app#1512]
Android version: 10 (API Level 29)
Device model: SM-J400F

The app crashes while trying to start VPN service with log below:
Logcat on crash
```
06-05 06:53:47.133 24396     0 E Go      : panic: runtime error: index out of range [-1]
06-05 06:53:47.134 24396     0 E Go      : 
06-05 06:53:47.134 24396     0 E Go      : goroutine 71 [running]:
06-05 06:53:47.134 24396     0 E Go      : github.com/celzero/firestack/intra/netstack.(*supervisor).queuePacket(0x9ce14240, 0x9ce2a388, 0x0)
06-05 06:53:47.134 24396     0 E Go      : 	/home/jitpack/build/intra/netstack/forwarders.go:271 +0x584
06-05 06:53:47.134 24396     0 E Go      : github.com/celzero/firestack/intra/netstack.(*readVDispatcher).dispatch(0x9ce14270)
06-05 06:53:47.134 24396     0 E Go      : 	/home/jitpack/build/intra/netstack/dispatchers.go:253 +0x544
06-05 06:53:47.134 24396     0 E Go      : github.com/celzero/firestack/intra/netstack.(*endpoint).dispatchLoop(0x9ccce360, {0xbd7becb0, 0x9ce14270})
06-05 06:53:47.134 24396     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:461 +0x304
06-05 06:53:47.134 24396     0 E Go      : created by github.com/celzero/firestack/intra/netstack.(*endpoint).Attach in goroutine 34
06-05 06:53:47.134 24396     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:305 +0x288
--------- beginning of crash
06-05 06:53:47.135 24396 24577 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 24577 (Thread-17), pid 24396 (elzero.bravedns)
```

I have downgraded to version `v0.5.5l` which doesn't suffer from problem described above

**Comment by timespace314** [comment]
Hmm found similar issue https://github.com/celzero/rethink-app/issues/1484
