### ISSUE TITLE
BugReportZipper.copy: failed: invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1557]
```java
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper: Work [ id=1407d154-220f-4b8c-9e12-9ce5696594b3, tags={ com.celzero.bravedns.scheduler.BugReportCollector, ScheduledCollectAppExit
InfoJob } ] failed because it threw an exception/error
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.util.zip.ZipException: invalid LOC header (bad signature)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(Unknown Source:20)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at androidx.work.impl.utils.futures.AbstractFuture.get(SourceFile:0)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at androidx.work.impl.WorkerWrapper$2.run(Unknown Source:4)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at androidx.work.impl.utils.SerialExecutorImpl$Task.run(Unknown Source:2)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.lang.Thread.run(Thread.java:920)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper: Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.ZipFile.read(Native Method)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.ZipFile.access$1400(ZipFile.java:64)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:810)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:479)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:177)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:141)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at com.celzero.bravedns.scheduler.BugReportZipper.copy(Unknown Source:0)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at com.celzero.bravedns.scheduler.BugReportZipper.handleOlderFiles(Unknown Source:90)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at com.celzero.bravedns.scheduler.BugReportZipper.rezipAll(Unknown Source:104)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at com.celzero.bravedns.scheduler.BugReportCollector.addToZip(Unknown Source:13)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at com.celzero.bravedns.scheduler.BugReportCollector.doWork(Unknown Source:110)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(Unknown Source:32)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
06-18 18:29:31.183  5427  5472 E WM-WorkerWrapper:      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
06-18 18:29:31.183  5427  5472 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=1407d154-220f-4b8c-9e12-9ce5696594b3, tags={ com.celzero.bravedns.scheduler.BugReportCollecto
r, ScheduledCollectAppExitInfoJob } ]

```

**Comment by ignoramous** [comment]
Need to redo this. Check comments on the commit: https://github.com/hussainmohd-a/rethink-app/commit/16c9e9494bf25ad9344c5b9bfaca758003447589
