### ISSUE TITLE
ClosedSendChannelException in NetLogBatcher.txswap(NetLogBatcher.kt:125)

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1569]
tap on start/stop furiously and...

```jq
06-24 22:27:22.643 14232 18937 D VpnLifecycle: init remote rdns mode            
06-24 22:27:22.646 14232 18398 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-12
06-24 22:27:22.646 14232 18398 E AndroidRuntime: Process: com.celzero.bravedns, PID: 14232
06-24 22:27:22.646 14232 18398 E AndroidRuntime: kotlinx.coroutines.channels.ClosedSendChannelException: Channel was closed
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at kotlinx.coroutines.channels.BufferedChannel.getSendException(BufferedChannel.kt:1726)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at kotlinx.coroutines.channels.ConflatedBufferedChannel.send$suspendImpl(ConflatedBufferedChannel.kt:46)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at kotlinx.coroutines.channels.ConflatedBufferedChannel.send(Unknown Source:0)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at com.celzero.bravedns.util.NetLogBatcher.txswap(NetLogBatcher.kt:125)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at com.celzero.bravedns.util.NetLogBatcher.access$txswap(NetLogBatcher.kt:40)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at com.celzero.bravedns.util.NetLogBatcher$add$2.invokeSuspend(NetLogBatcher.kt:141)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.util.concurrent.FutureTask.run(FutureTask.java:264)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--at java.lang.Thread.run(Thread.java:1012)
06-24 22:27:22.646 14232 18398 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(writeConsoleLog), StandaloneCoroutine{Cancelling}@914585d, Dispatchers.IO]
06-24 22:27:22.646 14232 18398 I Process : Sending signal. PID: 14232 SIG: 9 
```

**Comment by hussainmohd-a** [comment]
Now, for every new scope, the batchers are recreated, which will avoid the send-on-closed-channel.

Fix: https://github.com/celzero/rethink-app/pull/1581/commits/779311cb374ffea228be0712a5474f9fab7e4984
