### ISSUE TITLE
IllegalStateException accessing viewBinding after Lifecycle is destroyed in UniversalFirewallSettingsActivity.stopShimmer

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1573]
```
06-27 03:50:54.748  1792  5146 D TaskFragmentExtImpl: remove ActivityRecord{f57313e u0 com.celzero.bravedns/.ui.activity.UniversalFirewallSettingsActivity t-1 f}} to mActivityRecordSum = Counter{ com.celzero.bravedns/.ui.HomeScreenActivity(1) com.celzero.bravedns/.ui.activity.FirewallActivity(1) }
06-27 03:50:54.756  1792  1832 D OplusSplitScreenManagerService: com.celzero.bravedns supportsSplitScreen by forceResizable activity return:true
06-27 03:50:54.878 20110 20110 E AndroidRuntime: FATAL EXCEPTION: main          
06-27 03:50:54.878 20110 20110 E AndroidRuntime: Process: com.celzero.bravedns, PID: 20110
06-27 03:50:54.878 20110 20110 E AndroidRuntime: java.lang.IllegalStateException: Accessing viewBinding after Lifecycle is destroyed or hasn't been created yet. The instance of viewBinding isn't cached.
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.runStrictModeChecks(ViewBindingProperty.kt:112)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:91)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:71)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity.getB(UniversalFirewallSettingsActivity.kt:52)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity.stopShimmer(UniversalFirewallSettingsActivity.kt:420)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity.access$stopShimmer(UniversalFirewallSettingsActivity.kt:50)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity$updateStats$1$1.invokeSuspend$lambda$0(UniversalFirewallSettingsActivity.kt:386)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity$updateStats$1$1.$r8$lambda$V01zINxJ5gtXJt9JcBMVwvcYLxo(Unknown Source:0)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.celzero.bravedns.ui.activity.UniversalFirewallSettingsActivity$updateStats$1$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8826)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
06-27 03:50:54.878 20110 20110 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/1581/commits/eb578e2fa547b3c21658f781bd37b2b497524cc7
