### ISSUE TITLE
NetworkLogsActivity: java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#1578]
```
FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:11174).state:11158 androidx.recyclerview.widget.RecyclerView{6334fd7 VFED..C.. ......ID 5,153-1075,1314 #7f090504 app:id/recycler_connection viewInfo = }, adapter:com.celzero.bravedns.adapter.RethinkLogAdapter@2bd7727, layout:androidx.recyclerview.widget.LinearLayoutManager@bec933, context:com.celzero.bravedns.ui.activity.NetworkLogsActivity@81be95c
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6821)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
	at android.view.Choreographer.doFrame(Choreographer.java:984)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
[336ecd1 Application Error: com.celzero.bravedns#41011](this:0xb400007a857fd8f8,id:-1,api:0,p:-1,c:-1) id info cannot be read from '336ecd1 Application Error: com.celzero.bravedns#41011'
[Application Error: com.celzero.bravedns#41013](this:0xb400007ab4f858f8,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Application Error: com.celzero.bravedns#41013'
[Surface(name=336ecd1 Application Error: com.celzero.bravedns)/@0x5e5841f - animation-leash of window_animation#41014](this:0xb400007ab49b18f8,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=336ecd1 Application Error: com.celzero.bravedns)/@0x5e5841f - animation-leash of window_animation#41014'
[Surface(name=336ecd1 Application Error: com.celzero.bravedns)/@0x5e5841f - animation-leash of window_animation#41018](this:0xb400007aa78618f8,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=336ecd1 Application Error: com.celzero.bravedns)/@0x5e5841f - animation-leash of window_animation#41018'
RemoteException caught trying to send a callback msg for NetworkRequest [ TRACK_DEFAULT id=6432, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10458 RequestorUid: 10458 RequestorPkg: com.celzero.bravedns UnderlyingNetworks: Null] ]
```

**Comment by hussainmohd-a** [comment]
Related: https://github.com/celzero/rethink-app/issues/1601

**Comment by hussainmohd-a** [comment]
https://github.com/celzero/rethink-app/pull/1581/commits/e165be71d40656c42ca8b30fb13706da3303d9ee
https://github.com/celzero/rethink-app/pull/1581/commits/fd66e9c0a80050b6c11e75cc06a65f877566e3a2
