### ISSUE TITLE
v55o: IndexOutOfBoundsException in NetworkLogsActivity via Recycler.validateViewHolderForOffsetPosition

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1664]
```
08-28 01:32:17.767 23474 23474 E AndroidRuntime: Process: com.celzero.bravedns, PID: 23474
08-28 01:32:17.767 23474 23474 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionConnectionTrackerViewHolder{fcd17d9 position=112 id=-1, oldPos=211, pLpos:112 scrap [attachedScrap] tmpDetached no parent} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{590ca8b VFED..C.. ........ 5,153-1075,1314 #7f09054e app:id/recycler_connection viewInfo = }, adapter:com.celzero.bravedns.adapter.ConnectionTrackerAdapter@29d1a40, layout:androidx.recyclerview.widget.LinearLayoutManager@56195a5, context:com.celzero.bravedns.ui.activity.NetworkLogsActivity@cecc4a8
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:984)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8826)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
08-28 01:32:17.767 23474 23474 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

**Comment by ignoramous** [comment]
```
09-23 07:15:55.283  7701  7701 E AndroidRuntime: FATAL EXCEPTION: main          
09-23 07:15:55.283  7701  7701 E AndroidRuntime: Process: com.celzero.bravedns, PID: 7701
09-23 07:15:55.283  7701  7701 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionConnectionTrackerViewHolder{1fcff7e position=52 id=-1, oldPos=60, pLpos:52 scrap [attachedScrap] tmpDetached no parent} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{6b53f7 VFED..C.. ........ 5,153-1075,1314 #7f090563 app:id/recycler_connection viewInfo = }, adapter:com.celzero.bravedns.adapter.ConnectionTrackerAdapter@e5d1059, layout:androidx.recyclerview.widget.LinearLayoutManager@4e78bb1, context:com.celzero.bravedns.ui.activity.NetworkLogsActivity@cbcdafa
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:984)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8839)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
09-23 07:15:55.283  7701  7701 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
09-23 07:15:55.301  2109  8022 W OplusEapManager handleErrorInfo sendEvent: : com.celzero.bravedns happenedcrash
```

**Comment by ignoramous** [comment]
From yest:

```
04-30 23:38:48.523 21751 21751 E AndroidRuntime: FATAL EXCEPTION: main          
04-30 23:38:48.523 21751 21751 E AndroidRuntime: Process: com.celzero.bravedns, PID: 21751
04-30 23:38:48.523 21751 21751 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:2).state:34911 com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{bd4e353 VFED..... ......I. 0,161-1080,1319 #7f0905c8 app:id/recycler_query viewInfo = }, adapter:com.celzero.bravedns.adapter.DnsLogAdapter@af0e7f9, layout:androidx.recyclerview.widget.LinearLayoutManager@60011a3, context:com.celzero.bravedns.ui.activity.NetworkLogsActivity@f6a60bb
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6821)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:984)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8839)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
04-30 23:38:48.523 21751 21751 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by ignoramous** [comment]
```
08-19 06:34:02.442 17454 17454 E AndroidRuntime: FATAL EXCEPTION: main          
08-19 06:34:02.442 17454 17454 E AndroidRuntime: Process: com.celzero.bravedns, PID: 17454
08-19 06:34:02.442 17454 17454 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionAppListViewHolder{dde82d6 position=56 id=-1, oldPos=140, pLpos:56 scrap [attachedScrap] tmpDetached no parent} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{6b5bba9 VFED..C.. ........ 5,476-1075,1436 #7f090339 app:id/ffa_app_list aid=1073741833 viewInfo = }, adapter:com.celzero.bravedns.adapter.FirewallAppListAdapter@d9cc75d, layout:androidx.recyclerview.widget.LinearLayoutManager@2230625, context:com.celzero.bravedns.ui.activity.AppListActivity@2643ddc
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:984)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8839)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
08-19 06:34:02.442 17454 17454 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by ignoramous** [comment]
DNS Logs:

```hs
08-26 22:51:21.223 28764 28764 E AndroidRuntime: FATAL EXCEPTION: main          
08-26 22:51:21.223 28764 28764 E AndroidRuntime: Process: com.celzero.bravedns, PID: 28764
08-26 22:51:21.223 28764 28764 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 83(offset:77).state:31639 com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{716669a VFED..... ......I. 0,161-1080,1319 #7f090622 app:id/recycler_query viewInfo = }, adapter:com.celzero.bravedns.adapter.DnsLogAdapter@8f74a74, layout:androidx.recyclerview.widget.LinearLayoutManager@9233a92, context:com.celzero.bravedns.ui.activity.NetworkLogsActivity@747376e
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6821)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:468)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:984)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:958)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:257)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:368)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8839)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
08-26 22:51:21.223 28764 28764 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by hussainmohd-a** [comment]
The above mentioned commit seems to have fixed this issue. Will reopen if it persists.
