### ISSUE TITLE
v055o: ANR in DNS Logs

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1773]
In DNS Logs.

```jsx
11-08 18:39:58.115  8024 18680 I Quality :stackInfo 
:----- pid 8024 at 2024-11-08 18:39:58.104 -----;
Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=8024;
  at androidx.recyclerview.widget.AdapterHelper.findPositionOffset(AdapterHelper.java:472);
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:422);
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:4278);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4545);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346);
  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332);
  at android.widget.FrameLayout.onLayout(FrameLayout.java:270);
  at android.view.View.layout(View.java:24791);
  at android.view.ViewGroup.layout(ViewGroup.java:6555);
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407);
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720);  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1145);
  at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2047);
  at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2149);
  at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3867);
  at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:996);
  at android.view.View.dispatchTouchEvent(View.java:15805);
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3167);
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2835);
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173);
```

**Comment by hussainmohd-a** [comment]
Multiple improvements in commits b2cc8be9, 52b9d3f8 have addressed this issue.
Will reopen if it persists.
