### ISSUE TITLE
Crash when receiving download_complete broadcast intent

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#220]
```
01-05 16:38:28.319 24001 24001 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.celzero.bravedns (has extras) } in com.celzero.bravedns.ui.SettingsFragment$onComplete$1@bac489a
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:883)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:100)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: Caused b01-05 16:38:28.319 24001 24001 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.celzero.bravedns (has extras) } in com.celzero.bravedns.ui.SettingsFragment$onComplete$1@bac489a
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:883)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:100)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fragment SettingsFragment{a983d70} (95703d08-2fd3-4304-a99b-aa6520563bfd)} not attached to a context.
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.requireContext(Fragment.java:885)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getResources(Fragment.java:949)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getString(Fragment.java:971)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.celzero.bravedns.ui.SettingsFragment$onComplete$1.onReceive(SettingsFragment.kt:923)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--... 8 more     y: java.lang.IllegalStateException: Fragment SettingsFragment{a983d70} (95703d08-2fd3-4304-a99b-aa6520563bfd)} not attached to a context.
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.requireContext(Fragment.java:885)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getResources(Fragment.java:949)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getString(Fragment.java:971)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at com.celzero.bravedns.ui.SettingsFragment$onComplete$1.onReceive(SettingsFragment.kt:923)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
01-05 16:38:28.319 24001 24001 E AndroidRuntime: >--... 8 more     
```

**Comment by hussainmohd-a** [comment]
Logic of handling the local blocklist download is modified as part of v053c release. 
Now the app uses work manager to monitor the status of the download.
