### ISSUE TITLE
Homescreen crash in v053

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#227]
Crash:
```
01-14 22:44:04.798 24047 24047 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.celzero.bravedns/com.celzero.bravedns.ui.HomeScreenActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.celzero.bravedns.ui.HomeScreenSettingBottomSheet: could not find Fragment constructor
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:107)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:214)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:7682)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.celzero.bravedns.ui.HomeScreenSettingBottomSheet: could not find Fragment constructor
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.Fragment.instantiate(Fragment.java:612)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:88)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2711)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:296)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:269)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenActivity.onCreate(HomeScreenActivity.kt:137)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.Activity.performCreate(Activity.java:7815)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.Activity.performCreate(Activity.java:7804)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--... 11 more                 
01-14 22:44:04.798 24047 24047 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: com.celzero.bravedns.ui.HomeScreenSettingBottomSheet.<init> []
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at java.lang.Class.getConstructor0(Class.java:2332)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at java.lang.Class.getConstructor(Class.java:1728)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--at androidx.fragment.app.Fragment.instantiate(Fragment.java:597)
01-14 22:44:04.798 24047 24047 E AndroidRuntime: >--... 25 more 
```

**Comment by ignoramous** [comment]
Fixed.
