### ISSUE TITLE
ClassNotFoundException hit once when opening the app from foreground notification

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#231]
Doesn't happen always. It happened this once.

```
01-22 23:54:55.794  2124 18838 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/lib/arm64, /data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:370)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2399)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2356)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.app.ContextImpl.createApplicationContext(ContextImpl.java:2182)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.content.ContextWrapper.createApplicationContext(ContextWrapper.java:891)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.service.notification.StatusBarNotification.getPackageContext(StatusBarNotification.java:421)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at com.android.systemui.statusbar.notification.row.NotificationContentInflater$AsyncInflationTask.doInBackground(NotificationContentInflater.java:968)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at com.android.systemui.statusbar.notification.row.NotificationContentInflater$AsyncInflationTask.doInBackground(NotificationContentInflater.java:906)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-22 23:54:55.794  2124 18838 E LoadedApk: >---at java.lang.Thread.run(Thread.java:919)

```

```
01-22 23:54:55.708  2124  2124 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/lib/arm64, /data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:370)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2311)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2217)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.policy.PreviewInflater.inflateWidgetView(PreviewInflater.java:82)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.policy.PreviewInflater.inflatePreview(PreviewInflater.java:70)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.policy.PreviewInflater.inflatePreview(PreviewInflater.java:58)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.updateLeftPreview(KeyguardBottomAreaView.java:972)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.updateLeftAffordance(KeyguardBottomAreaView.java:1034)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.onFinishInflate(KeyguardBottomAreaView.java:322)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.NotificationPanelView.reInflateViews(NotificationPanelView.java:572)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.NotificationPanelView.onOverlayChanged(NotificationPanelView.java:542)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:125)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.Dependency.lambda$onConfigurationChanged$4(Dependency.java:576)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.-$$Lambda$Dependency$luNuSkkTPcUk3WR4ZubVPeHwRuQ.accept(Unknown Source:2)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:185)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.Iterator.forEachRemaining(Iterator.java:116)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:435)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.Dependency.onConfigurationChanged(Dependency.java:576)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:276)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:5554)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5759)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread.handleApplicationInfoChanged(ActivityThread.java:5820)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.os.Handler.dispatchMessage(Handler.java:107)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.os.Looper.loop(Looper.java:214)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at android.app.ActivityThread.main(ActivityThread.java:7682)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at java.lang.reflect.Method.invoke(Native Method)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-22 23:54:55.708  2124  2124 E LoadedApk: >---at com.android.internal 
```

**Comment by ignoramous** [comment]
The phone was also resuming from "screen pinning", if that's relevant.

Also, from the logs, it further looks like there are a lot of apps that crashed as well, with an identical exception moments before. For ex:

```
01-22 23:54:55.419  1333  1426 E PackageManager: java.util.concurrent.TimeoutException: [Optimistic Bind] Didn't bind to resolver in time!
01-22 23:54:55.419  1333  1426 E PackageManager: >--at com.android.server.pm.InstantAppResolverConnection.waitForBindLocked(InstantAppResolverConnection.java:161)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at com.android.server.pm.InstantAppResolverConnection.bind(InstantAppResolverConnection.java:226)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at com.android.server.pm.InstantAppResolverConnection.lambda$optimisticBind$0$InstantAppResolverConnection(InstantAppResolverConnection.java:256)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at com.android.server.pm.-$$Lambda$InstantAppResolverConnection$D-JKXi4qrYjnPQMOwj8UtfZenps.run(Unknown Source:2)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at android.os.Handler.handleCallback(Handler.java:883)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at android.os.Handler.dispatchMessage(Handler.java:100)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at android.os.Looper.loop(Looper.java:214)
01-22 23:54:55.419  1333  1426 E PackageManager: >--at android.os.HandlerThread.run(HandlerThread.java:67)
01-22 23:54:55.456  2124  2124 E LoadedApk: Unable to instantiate appComponentFactory
01-22 23:54:55.456  2124  2124 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/lib/arm64, /data/app/com.celzero.bravedns-O6itWt24ZZExjl34mACMbw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:370)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.app.ActivityThread.handleApplicationInfoChanged(ActivityThread.java:5804)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.os.Handler.dispatchMessage(Handler.java:107)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.os.Looper.loop(Looper.java:214)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at android.app.ActivityThread.main(ActivityThread.java:7682)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at java.lang.reflect.Method.invoke(Native Method)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-22 23:54:55.456  2124  2124 E LoadedApk: >---at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by ignoramous** [comment]
This bug exists _only_ for future reference. I don't believe there's anything to do be done here. Closing...
