### ISSUE TITLE
ANR whilst disconnecting tunnel

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#244]
If possible, move operations interacting with `BraveVPNService` and/or `GoVpnAdapter` off the main-thread. Perhaps we could follow the model of triggering state-transition through `LiveData` that's used by [Mozilla's Guardian VPN Android app](https://github.com/mozilla-mobile/guardian-vpn-android/blob/13acfd327/app/src/main/java/org/mozilla/firefox/vpn/main/vpn/GuardianVpnManager.kt#L43-L52).

```
"main" prio=5 tid=1 Native                                                      
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x72de3a78 self=0x7004209c00    
  | sysTid=7454 nice=0 cgrp=default sched=0/0 handle=0x7005777ed0               
  | state=S schedstat=( 105299853486 33594648138 164574 ) utm=7828 stm=2701 core=6 HZ=100
  | stack=0x7ff4481000-0x7ff4483000 stackSize=8192KB                            
  | held mutexes=                                                               
  kernel: (couldn't read /proc/self/task/7454/stack)                            
  native: #00 pc 0000000000203c0c  /data/app/com.celzero.bravedns-Kc7nGZjRdwCmpKai1wxqNA==/base.apk (offset 944000) (runtime.futex+28)
  at tunnel.Tunnel$proxyIntraTunnel.disconnect(Native method)                   
  at com.celzero.bravedns.net.go.GoVpnAdapter.close(GoVpnAdapter.java:460)      
  - locked <0x008075c0> (a com.celzero.bravedns.net.go.GoVpnAdapter)            
  at com.celzero.bravedns.service.BraveVPNService.stopVpnAdapter(BraveVPNService.kt:833)
  - locked <0x0d12d2f9> (a com.celzero.bravedns.service.VpnController)          
  at com.celzero.bravedns.service.BraveVPNService.signalStopService(BraveVPNService.kt:816)
  at com.celzero.bravedns.service.VpnController.stop(VpnController.kt:116)      
  - locked <0x0d12d2f9> (a com.celzero.bravedns.service.VpnController)          
  at com.celzero.bravedns.ui.HomeScreenFragment.stopDnsVpnService(HomeScreenFragment.kt:814)
  at com.celzero.bravedns.ui.HomeScreenFragment.handleStartBtnClickEvent(HomeScreenFragment.kt:455)
  at com.celzero.bravedns.ui.HomeScreenFragment.access$handleStartBtnClickEvent(HomeScreenFragment.kt:85)
  at com.celzero.bravedns.ui.HomeScreenFragment$initializeClickListeners$8.onClick(HomeScreenFragment.kt:374)
  at android.view.View.performClick(View.java:7201)                             
  at android.view.View.performClickInternal(View.java:7170)                     
  at android.view.View.access$3500(View.java:806)                               
  at android.view.View$PerformClick.run(View.java:27562)                        
  at android.os.Handler.handleCallback(Handler.java:883)                        
  at android.os.Handler.dispatchMessage(Handler.java:100)                       
  at android.os.Looper.loop(Looper.java:214)                                    
  at android.app.ActivityThread.main(ActivityThread.java:7682)                  
  at java.lang.reflect.Method.invoke(Native method)                             
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)                                                                               
```

**Comment by ignoramous** [comment]
Handled via #321
