### ISSUE TITLE
Window leaking dialog?

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#253]
```
03-21 04:02:09.053 13587 13587 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
03-21 04:02:09.067 13587 13813 D OpenGLRenderer: endAllActiveAnimators on 0x7eeb8a1b00 (AlertController$RecycleListView) with handle 0x7eeaf12100
03-21 04:02:09.092 13587 13587 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
03-21 04:02:09.116 13587 19167 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d9b8598[HomeScreenActivity]
03-21 04:02:09.129 13587 13587 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
03-21 04:02:10.136 13587 13813 D OpenGLRenderer: endAllActiveAnimators on 0x7e7cec3a00 (AlertController$RecycleListView) with handle 0x7eeaf1cb40
03-21 04:02:10.152 13587 19167 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@db8849a[HomeScreenActivity]
03-21 04:02:10.161 13587 13587 W RethinkDNS: Unregister receiver exception
03-21 04:02:10.178 13587 13587 E WindowManager: 
03-21 04:02:10.178 13587 13587 E WindowManager: android.view.WindowLeaked: Activity com.celzero.bravedns.ui.HomeScreenActivity has leaked window DecorView@cf19c35[HomeScreenActivity] that was originally added here
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:642)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:388)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.app.Dialog.show(Dialog.java:342)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.showDialogForTheme(SettingsFragment.kt:581)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.access$showDialogForTheme(SettingsFragment.kt:79)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$17.onClick(SettingsFragment.kt:472)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.View.performClick(View.java:7201)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.View.performClickInternal(View.java:7170)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.View.access$3500(View.java:806)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.view.View$PerformClick.run(View.java:27562)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-21 04:02:10.178 13587 13587 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 04:02:10.180 13587 13587 E WindowManager: 
03-21 04:02:10.187 13587 13587 E WindowManager: android.view.WindowLeaked: Activity com.celzero.bravedns.ui.HomeScreenActivity has leaked window DecorView@b95d3dd[HomeScreenActivity] that was originally added here
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:642)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:388)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.app.Dialog.show(Dialog.java:342)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.showDialogForTheme(SettingsFragment.kt:581)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.access$showDialogForTheme(SettingsFragment.kt:79)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$17.onClick(SettingsFragment.kt:472)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.View.performClick(View.java:7201)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.View.performClickInternal(View.java:7170)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.View.access$3500(View.java:806)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.view.View$PerformClick.run(View.java:27562)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-21 04:02:10.187 13587 13587 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 04:02:10.189 13587 13587 E WindowManager: 
03-21 04:02:10.189 13587 13587 E WindowManager: android.view.WindowLeaked: Activity com.celzero.bravedns.ui.HomeScreenActivity has leaked window DecorView@5ec1bc2[HomeScreenActivity] that was originally added here
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:642)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:388)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.app.Dialog.show(Dialog.java:342)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.showDialogForTheme(SettingsFragment.kt:581)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.access$showDialogForTheme(SettingsFragment.kt:79)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$17.onClick(SettingsFragment.kt:472)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.View.performClick(View.java:7201)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.View.performClickInternal(View.java:7170)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.View.access$3500(View.java:806)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.view.View$PerformClick.run(View.java:27562)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-21 04:02:10.189 13587 13587 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 04:02:10.190 13587 13587 E WindowManager: 
03-21 04:02:10.194 13587 13587 E WindowManager: android.view.WindowLeaked: Activity com.celzero.bravedns.ui.HomeScreenActivity has leaked window DecorView@e396cf0[HomeScreenActivity] that was originally added here
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:642)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:388)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.app.Dialog.show(Dialog.java:342)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.showDialogForTheme(SettingsFragment.kt:581)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.access$showDialogForTheme(SettingsFragment.kt:79)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$17.onClick(SettingsFragment.kt:472)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.View.performClick(View.java:7201)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.View.performClickInternal(View.java:7170)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.View.access$3500(View.java:806)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.view.View$PerformClick.run(View.java:27562)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-21 04:02:10.194 13587 13587 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 04:02:10.196 13587 13587 E WindowManager: 
03-21 04:02:10.196 13587 13587 E WindowManager: android.view.WindowLeaked: Activity com.celzero.bravedns.ui.HomeScreenActivity has leaked window DecorView@b1fb599[HomeScreenActivity] that was originally added here
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:642)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:388)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.app.Dialog.show(Dialog.java:342)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.showDialogForTheme(SettingsFragment.kt:581)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment.access$showDialogForTheme(SettingsFragment.kt:79)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$17.onClick(SettingsFragment.kt:472)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.View.performClick(View.java:7201)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.View.performClickInternal(View.java:7170)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.View.access$3500(View.java:806)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.view.View$PerformClick.run(View.java:27562)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-21 04:02:10.204 13587 13587 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 04:02:10.278 13587 13587 D RethinkDNS: Refresh database is called
03-21 04:02:10.278 13587 13587 D RethinkDNS: Settings Fragment- isLockDownEnabled - false 
```

**Comment by ignoramous** [comment]
Related but not the same issue: https://github.com/celzero/rethink-app/commit/1bb47828e08791ff76d7d4d223864a22447ff03f

**Comment by ignoramous** [comment]
Attempted fix. Test in production in-progress...
