### ISSUE TITLE
App crashes when local blocklist's enabled

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#262]
App crashes when the local blocklist is enabled in SettingsFragment. To set the local blocklist in the GO module, the BraveDNS object will be created with `Dnsx.newBraveDNSLocal()` function call. User reported the below error while the local blocklist is enabled.   

> _go.Universe$proxyerror: invalid character '\\x00' looking for beginning of value_

Below log for reference. 
```
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: FATAL EXCEPTION: main
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: Process: com.celzero.bravedns, PID: 24183
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:606)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	... 1 more
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: Caused by: go.Universe$proxyerror: invalid character '\\x00' looking for beginning of value
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at dnsx.Dnsx.newBraveDNSLocal(Native Method)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.celzero.bravedns.data.AppMode.getBraveDNS(AppMode.kt:213)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.celzero.bravedns.ui.SettingsFragment.setBraveDNSLocal(SettingsFragment.kt:856)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.celzero.bravedns.ui.SettingsFragment.access$setBraveDNSLocal(SettingsFragment.kt:80)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$6.onClick(SettingsFragment.kt:336)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:16104)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.widget.CompoundButton.performClick(CompoundButton.java:155)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30250)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8425)
04-06 01:56:01.597 10675 24183 24183 E AndroidRuntime: 	... 3 more
```

**Comment by ignoramous** [comment]
Looks like the blocklist.json file is empty.

```
04-06 08:17:04.486 10675  9344 13406 I GoLog   : file read successful : /data/data/com.celzero.bravedns/files/1611913996821/rd.txt
04-06 08:17:04.486 10675  9344 13406 I GoLog   : file byte length :  4028044    
04-06 08:17:04.529 10675  9344 13409 I GoLog   : TD_buf Length : 28643863       
04-06 08:17:04.529 10675  9344 13409 I GoLog   : RD_buf Length : 2014022        
04-06 08:17:04.529 10675  9344 13409 I GoLog   : error: zero len blocklist json 

```
