### ISSUE TITLE
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#264]
```
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime: Process: com.celzero.bravedns, PID: 4578
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:361)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getLifecycleOwner(FragmentViewBindings.kt:15)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getLifecycleOwner(FragmentViewBindings.kt:11)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:60)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:45)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at com.celzero.bravedns.ui.SettingsFragment.getB(Unknown Source:7)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at com.celzero.bravedns.ui.SettingsFragment.access$getB$p(SettingsFragment.kt:80)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at com.celzero.bravedns.ui.SettingsFragment$initClickListeners$6$1.onFinish(SettingsFragment.kt:356)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:106)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:246)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:8425)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
04-06 01:48:36.373 10675  4578  4578 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by ignoramous** [comment]
@hussainmohd-a has this been fixed?

**Comment by hussainmohd-a** [comment]
Fixed. Part of Pull request #354

Issue was with the viewBinding library: by.kirich1409.viewbindingdelegate
which is now fixed with the latest version of the library (1.5.0)
