### ISSUE TITLE
android.view.InflateException in FirewallAppListAdapter#getGroupView

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#265]
```
[04-07 10:36:27.975 1951:1951 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.celzero.bravedns, PID: 1951
android.view.InflateException: Binary XML file line #93: Binary XML file line #93: Error inflating class <unknown>
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.celzero.bravedns.adapter.FirewallAppListAdapter.getGroupView(FirewallAppListAdapter.kt:225)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
	at android.widget.AbsListView.obtainView(AbsListView.java:2474)
	at android.widget.ListView.makeAndAddView(ListView.java:1965)
	at android.widget.ListView.fillDown(ListView.java:762)
	at android.widget.ListView.fillFromTop(ListView.java:823)
	at android.widget.ListView.layoutChildren(ListView.java:1746)
	at android.widget.AbsListView.onLayout(AbsListView.java:2235)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2757)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2560)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2263)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1329)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

**Comment by ignoramous** [comment]
User reported to have happened on their Android 6 device.

**Comment by hussainmohd-a** [comment]
Fixed as part of v053d release. For android version 6, the support library were used which was causing the issue. 
useSupportLibrary is set as false in build.gradle file solved the issue.
