### ISSUE TITLE
NPE after Glide fails to fetch favico

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#267]
```
04-15 02:22:25.262  3501  3501 W Glide   : Load failed for https://icons.duckduckgo.com/ip2/prilik.com.ico with size [71x71]
04-15 02:22:25.262  3501  3501 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
04-15 02:22:25.262  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.262  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/prilik.com.ico)
04-15 02:22:25.262  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.262  3501  3501 W Glide   :   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
04-15 02:22:25.262  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.262  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/prilik.com.ico)
04-15 02:22:25.262  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.262  3501  3501 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
04-15 02:22:25.262  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.262  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/prilik.com.ico)
04-15 02:22:25.262  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.262  3501  3501 W Glide   :       Cause (1 of 1): class java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/prilik.com.ico
04-15 02:22:25.263  3501  3501 I Glide   : Root cause (1 of 1)                  
04-15 02:22:25.263  3501  3501 I Glide   : java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/prilik.com.ico
04-15 02:22:25.263  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
04-15 02:22:25.263  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-15 02:22:25.263  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-15 02:22:25.263  3501  3501 I Glide   :  at java.lang.Thread.run(Thread.java:919)
04-15 02:22:25.263  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

```
04-15 02:22:25.550  3501  3501 W Glide   : Load failed for https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico with size [71x71]
04-15 02:22:25.550  3501  3501 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
04-15 02:22:25.550  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.550  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.550  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.550  3501  3501 W Glide   :   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
04-15 02:22:25.550  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.550  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.550  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.550  3501  3501 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
04-15 02:22:25.550  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.550  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.550  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.550  3501  3501 W Glide   :       Cause (1 of 1): class java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico
04-15 02:22:25.550  3501  3501 I Glide   : Root cause (1 of 1)                  
04-15 02:22:25.550  3501  3501 I Glide   : java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico
04-15 02:22:25.550  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
04-15 02:22:25.550  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-15 02:22:25.550  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-15 02:22:25.550  3501  3501 I Glide   :  at java.lang.Thread.run(Thread.java:919)
04-15 02:22:25.550  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

```
04-15 02:22:25.739  3501  3501 W Glide   : Load failed for https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico with size [71x71]
04-15 02:22:25.739  3501  3501 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
04-15 02:22:25.739  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.739  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.739  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.739  3501  3501 W Glide   :   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
04-15 02:22:25.739  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.739  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.739  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.739  3501  3501 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
04-15 02:22:25.739  3501  3501 W Glide   : There was 1 cause:                   
04-15 02:22:25.739  3501  3501 W Glide   : java.io.FileNotFoundException(https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico)
04-15 02:22:25.739  3501  3501 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-15 02:22:25.739  3501  3501 W Glide   :       Cause (1 of 1): class java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico
04-15 02:22:25.740  3501  3501 I Glide   : Root cause (1 of 1)                  
04-15 02:22:25.740  3501  3501 I Glide   : java.io.FileNotFoundException: https://icons.duckduckgo.com/ip2/pauldone.blogspot.com.ico
04-15 02:22:25.740  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
04-15 02:22:25.740  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-15 02:22:25.740  3501  3501 I Glide   :  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-15 02:22:25.740  3501  3501 I Glide   :  at java.lang.Thread.run(Thread.java:919)
04-15 02:22:25.740  3501  3501 I Glide   :  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

```yaml
04-15 02:22:25.742  3501  3501 E AndroidRuntime: FATAL EXCEPTION: main          
04-15 02:22:25.742  3501  3501 E AndroidRuntime: Process: com.celzero.bravedns, PID: 3501
04-15 02:22:25.742  3501  3501 E AndroidRuntime: java.lang.NullPointerException 
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.celzero.bravedns.ui.DNSBlockListBottomSheetFragment.getB(DNSBlockListBottomSheetFragment.kt:52)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.celzero.bravedns.ui.DNSBlockListBottomSheetFragment.updateImage(DNSBlockListBottomSheetFragment.kt:167)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.celzero.bravedns.ui.DNSBlockListBottomSheetFragment.access$updateImage(DNSBlockListBottomSheetFragment.kt:48)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.celzero.bravedns.ui.DNSBlockListBottomSheetFragment$updateImage$1$onLoadFailed$1.run(DNSBlockListBottomSheetFragment.kt:155)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:883)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:100)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7682)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-15 02:22:25.742  3501  3501 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
04-15 02:22:25.751  1331 19318 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

```

**Comment by hussainmohd-a** [comment]
Fixed in commit https://github.com/celzero/rethink-app/commit/2d8032f544323283e7ed3d4910062fec1d96b4d4
