### ISSUE TITLE
Crash on Android 12.1 

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#325]
A user says,

> Just wanted to say that rethinkdns app crashes as soon as i start the firewall, or dns or anything at all on Android 12 beta 2.1

Investigate.

**Comment by ignoramous** [comment]
```
FATAL EXCEPTION: main
Process: com.celzero.bravedns, PID: 1530
java.lang.SecurityException: Settings key: <always_on_vpn_app> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
 at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2795)
 at android.provider.Settings$Secure.getStringForUser(Settings.java:5731)
 at android.provider.Settings$Secure.getString(Settings.java:5687)
 at com.celzero.bravedns.ui.HomeScreenFragment.checkForPrivateDNSandAlwaysON(HomeScreenFragment.kt:313)
 at com.celzero.bravedns.ui.HomeScreenFragment.handleStartBtnClickEvent(HomeScreenFragment.kt:260)
 at com.celzero.bravedns.ui.HomeScreenFragment.access$handleStartBtnClickEvent(HomeScreenFragment.kt:63)
 at com.celzero.bravedns.ui.HomeScreenFragment$initializeClickListeners$8.onClick(HomeScreenFragment.kt:155)
 at android.view.View.performClick(View.java:7434)
 at android.view.View.performClickInternal(View.java:7411)
 at android.view.View.access$3700(View.java:835)
 at android.view.View$PerformClick.run(View.java:28640)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7796)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
```

**Comment by ignoramous** [comment]
Fixed in a yet-to-be-merged pull-request, but has been on test builds for two weeks now with no regressions.
