### ISSUE TITLE
AppManager, CalyxOS occasionally spell trouble for ConnectionCapabilityMonitor

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#327]
A user encountered a strange exception on CalyxOS with [MuntashirAkon's AppManager](https://github.com/MuntashirAkon/AppManager) installed (though, it wasn't used to remove permissions from either `uid` `0` or RethinkDNS itself).

A note from the user: I did not activly revoke permissions for rethinkdns. But by default the permission `android.permission.INTERACT_ACROSS_USERS`  is removed.

```
FATAL EXCEPTION: main
Process: com.celzero.bravedns, PID: 7496
java.lang.RuntimeException: Unable to start service com.celzero.bravedns.service.BraveVPNService@27b1f6c with Intent { cmp=com.celzero.bravedns/.service.BraveVPNService }: java.lang.SecurityException: Package android does not belong to 10097
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
 at android.app.ActivityThread.access$1800(ActivityThread.java:237)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7664)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.SecurityException: Package android does not belong to 10097
 at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
 at android.os.Parcel.createException(Parcel.java:2357)
 at android.os.Parcel.readException(Parcel.java:2340)
 at android.os.Parcel.readException(Parcel.java:2282)
 at android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:3648)
 at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3694)
 at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4088)
 at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4058)
 at com.celzero.bravedns.service.ConnectionCapabilityMonitor.<init>(ConnectionCapabilityMonitor.kt:44)
 at com.celzero.bravedns.service.BraveVPNService.onStartCommand(BraveVPNService.kt:630)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
 ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
 at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
 at com.android.server.ConnectivityService.ensureSufficientPermissionsForRequest(ConnectivityService.java:5631)
 at com.android.server.ConnectivityService.listenForNetwork(ConnectivityService.java:5875)
 at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1664)
 at android.os.Binder.execTransactInternal(Binder.java:1154)
```

**Comment by ignoramous** [comment]
Another set of logs from calyxos, may be due to the `Global VPN` feature?

```
05-12 13:54:43.544 17416 17452 E AndroidRuntime: Process: com.celzero.bravedns, PID: 17416
05-12 13:54:43.544 17416 17452 E AndroidRuntime: java.lang.SecurityException: getPackagesForUid: UID 10155 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES to access user .
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2409)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2392)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2334)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:5418)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1001)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:995)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:562)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1014)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.util.Utilities$Companion.getPackageInfoForUid(Utilities.kt:437)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker.fetchApplicationName(IPTracker.kt:97)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker.insertToDB(IPTracker.kt:88)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker.access$insertToDB(IPTracker.kt:42)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker$recordTransaction$1.invokeSuspend(IPTracker.kt:61)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker$recordTransaction$1.invoke(Unknown Source:8)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker$recordTransaction$1.invoke(Unknown Source:2)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.celzero.bravedns.service.IPTracker$io$1.invokeSuspend(IPTracker.kt:135)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
05-12 13:54:43.544 17416 17452 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.android.server.pm.PackageManagerService$ComputerEngine.enforceCrossUserOrProfilePermission(PackageManagerService.java:4639)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.android.server.pm.PackageManagerService$ComputerTracker.enforceCrossUserOrProfilePermission(PackageManagerService.java:5902)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.enforceCrossUserOrProfilePermission(PackageManagerService.java:12562)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.getPackagesForUid(PackageManagerService.java:10339)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2248)
05-12 13:54:43.544 17416 17452 E AndroidRuntime:
```

**Comment by ignoramous** [comment]
Apparently this is due to the new [_Global VPN_](https://calyxos.org/news/2021/09/02/feature-update/) setting introduced in a new CalyxOS update (Sep, 2021).

Dup: #150
