### ISSUE TITLE
Corruption reported by sqlite on database without warning

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#344]
App crashed and the reason was database corruption. Though rules sets with `SharedPreference` were not lost, everything else was. `AppInfoRepository` recovered by hydrating (via `RefreshDatabase.kt`) from `PackageManager#getInstalledPackages`, but the rest of the data was lost forever, with even default entries going empty; that is, after this happened, network logs, dns logs, all dns entires (dns-over-https, dns-proxy, dns-crypt) go empty, there's nothing to show in the UI... This was followed by inconsistency in what the connected-dns was (`free.bravedns.com`) and what was shown (`DoH 6`, the last connected DNS when the db was up and running). From the logs, there was no prior warning to be found of the database going kaput.

```
07-28 01:41:24.367 22304 22365 E SQLiteLog: (26) statement aborts at 12: [select count(*) from BlockedConnections where uid = -1000] file is not a database
07-28 01:41:24.368 22304 22365 E SupportSQLite: Corruption reported by sqlite on database: /data/user/0/com.celzero.bravedns/databases/bravedns.db
07-28 01:41:24.368 22304 22365 W SupportSQLite: deleting the database file: /data/user/0/com.celzero.bravedns/databases/bravedns.db
07-28 01:41:24.372 22304 22365 E AndroidRuntime: FATAL EXCEPTION: arch_disk_io_2
07-28 01:41:24.372 22304 22365 E AndroidRuntime: Process: com.celzero.bravedns, PID: 22304
07-28 01:41:24.372 22304 22365 E AndroidRuntime: java.lang.RuntimeException: Exception while computing database live data.
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at java.lang.Thread.run(Thread.java:919)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: file is not a database (code 26 SQLITE_NOTADB)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at com.celzero.bravedns.database.BlockedConnectionsDAO_Impl$10.call(BlockedConnectionsDAO_Impl.java:663)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at com.celzero.bravedns.database.BlockedConnectionsDAO_Impl$10.call(BlockedConnectionsDAO_Impl.java:657)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
07-28 01:41:24.372 22304 22365 E AndroidRuntime: >--... 3 more      
```

Handle such database corruption by:
1. Detecting it and informing the user via a dialog / notification that the database is being rebuilt because all state has been lost.
2. Hydrating the tables with seed data whenever they go empty.
3. Prompt for bug reports. #336 

Likely, we must move from using `GlobalScope` co-routines for table updates and use `viewModelScope` wherever appropriate. #243  

Possibly, buffer writes (batch-write) into network-log and dns-log tables. #343

**Comment by hussainmohd-a** [comment]
One of the possible case where the database corruption can happen is explained in the below link, 

https://www.fatalerrors.org/a/crash-sqlitedatabase-corruption-exception-file-is-encrypted-or-is-not-a-database.html

Adding the `setJournalMode(JournalMode.TRUNCATE)`  to the App database builder as suggested. 

```
Android 9 introduces a special mode of SQLiteDatabase called "write ahead logging", which allows the database to use journal_mode=WAL, while retaining the behavior of creating at most one connection per database.

WAL changes the way the database works and throws this exception in some states. You need to manually turn off the WAL mode according to the above solution to fix this problem.
```

**Comment by ignoramous** [comment]
Journal mode has been changed back to WAL (since the suggestion linked to from above isn't really based on any concrete facts or anything) since readers on the underlying sqlite3 tables has increased.

Besides, there's been a bunch of other improvements in batching writes (#343) and splitting away the write-heavy logs-related tables (ie, network log & dns log tables) in to its own database (#574), which should improve and isolate corruptions a bit.
