### ISSUE TITLE
Compatibility issues in pre-launch report: android.os.strictmode.NonSdkApiUsedViolation

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#379]
API `Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V`

Stack trace `StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V`

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java:84)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:983)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:816)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:704)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:326)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at com.celzero.bravedns.ui.FirewallActivity.onCreate(FirewallActivity.kt:55)
	at android.app.Activity.performCreate(Activity.java:7957)
	at android.app.Activity.performCreate(Activity.java:7946)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by hussainmohd-a** [comment]
This issue may be associated with Google- supplied library AndroidX. There is nothing we need to do at the moment. [Reference#1](https://stackoverflow.com/questions/52358496/setcontentview-is-using-non-sdk-interface/53736775#53736775), [Reference#2](https://stackoverflow.com/questions/56826517/google-play-report-unsupported-api-but-it-is-in-appcompat)

**Comment by hussainmohd-a** [comment]
Closing the issue as it is related to AndroidX library
