### ISSUE TITLE
DnsDetailActivity: Fragment not attached to a context

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#494]
`v053i`:

```
07-26 13:37:02.668 28820 28820 E AndroidRuntime: Process: com.celzero.bravedns, PID: 28820
07-26 13:37:02.668 28820 28820 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.celzero.bravedns/com.celzero.bravedns.ui.DnsDetailActivity}: java.lang.IllegalStateException: Fragment DnsConfigureFragment{41f5a23} (21486972-19ea-439c-942e-96228492f7b9) not attached to a context.
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5340)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5370)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:233)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8068)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Fragment DnsConfigureFragment{41f5a23} (21486972-19ea-439c-942e-96228492f7b9) not attached to a context.
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.Fragment.getString(Fragment.java:1053)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.celzero.bravedns.ui.DnsConfigureFragment.updateLocalBlocklistUi(DnsConfigureFragment.kt:101)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.celzero.bravedns.ui.DnsConfigureFragment.onBtmSheetDismiss(DnsConfigureFragment.kt:395)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet.onDismiss(LocalBlocklistsBottomSheet.kt:79)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.DialogFragment.onDestroyView(DialogFragment.java:792)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet.onDestroyView(LocalBlocklistsBottomSheet.kt:73)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3341)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:745)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:327)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2922)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:259)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.Activity.performDestroy(Activity.java:8251)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5325)
07-26 13:37:02.668 28820 28820 E AndroidRuntime: >--... 11 more    
```

**Comment by ignoramous** [comment]
This happens often. Not sure what the repro steps are.

**Comment by ignoramous** [comment]
See also: #391

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/hussainmohd-a/rethink-app/commit/7921848e84a3b4b3f3fc9d1f1a6fbd8cbca8bddf
