### ISSUE TITLE
Crash | Cannot access database on the main thread since it may potentially lock the UI for a long period of time

### ISSUE THREAD

**Issue by shuvashish76** [celzero/rethink-app#601]
Crash when I click on Copy as "RDNS + URL"

**Crash logs**

```
FATAL EXCEPTION: main
Process: com.celzero.bravedns, PID: 17545
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:469)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:525)
	at androidx.room.util.DBUtil.query(DBUtil.java:86)
	at com.celzero.bravedns.database.RethinkDnsEndpointDao_Impl.getRethinkPlusEndpoint(RethinkDnsEndpointDao_Impl.java:796)
	at com.celzero.bravedns.database.RethinkDnsEndpointDao$DefaultImpls.getRethinkPlusEndpoint$default(RethinkDnsEndpointDao.kt:81)
	at com.celzero.bravedns.database.RethinkDnsEndpointRepository.getRethinkPlusEndpoint(RethinkDnsEndpointRepository.kt:81)
	at com.celzero.bravedns.data.AppConfig.getRethinkPlusEndpoint(AppConfig.kt:674)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet$initializeClickListeners$3$1$1.invokeSuspend(LocalBlocklistsBottomSheet.kt:354)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet$initializeClickListeners$3$1$1.invoke(Unknown Source:8)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet$initializeClickListeners$3$1$1.invoke(Unknown Source:2)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet$go$1.invokeSuspend(LocalBlocklistsBottomSheet.kt:525)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:204)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet.ui(LocalBlocklistsBottomSheet.kt:516)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet.initializeClickListeners$lambda-5(LocalBlocklistsBottomSheet.kt:351)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet.$r8$lambda$q7d8PlAIaZRJwzCNSSgEFyLP2YE(Unknown Source:0)
	at com.celzero.bravedns.ui.LocalBlocklistsBottomSheet$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24774)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

followed by another crash when I just try to open the app from device launcher

```
FATAL EXCEPTION: main
Process: com.celzero.bravedns, PID: 17441
java.lang.RuntimeException: Unable to stop service com.celzero.bravedns.service.BraveVPNService@7566e1a: kotlin.UninitializedPropertyAccessException: lateinit property orbotStartStatusObserver has not been initialized
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3525)
	at android.app.ActivityThread.-wrap26(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property orbotStartStatusObserver has not been initialized
	at com.celzero.bravedns.service.BraveVPNService.unobserveOrbotStartStatus(BraveVPNService.kt:1148)
	at com.celzero.bravedns.service.BraveVPNService.onDestroy(BraveVPNService.kt:1552)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3507)
	... 8 more
```

**Device details**
App version: _**053k (22)**_
Android: 8.1.0
Model: Lenovo TB-8704X

**Comment by shuvashish76** [comment]
Just to mention here the new _v053k_ for some reason not blocking any ads (app updated without changing any configuration), switched to _v053j_ for the same reason. (probably not related to this issue)

**Comment by ignoramous** [comment]
> Crash when I click on Copy as "RDNS + URL"

Ah, yes. It is 100% reproducible. Annoying bug. We'll fix it, thanks.

> Just to mention here the new v053k for some reason not blocking any ads...

What did the *DNS logs* screen look like in `v053k`? Did it not show any `blocked` queries (you can filter just the blocked queries out to verify this).

**Comment by shuvashish76** [comment]
> What did the DNS logs screen look like in v053k? Did it not show any blocked queries (you can filter just the blocked queries out to verify this).

Yes, no blocked quires in DNS logs. But now reinstalled & everything working as expected🤷🏿‍♂️. I'll create separate issue if I face similar issue in future👍🏿

**Comment by ignoramous** [comment]
Thanks for your patience and bug reports (esp, complete with logcat output). Appreciate it.

Fixes in pipeline for the next minor release, `v053l`.
