### ISSUE TITLE
Crash while downloading Blocklists

### ISSUE THREAD

**Issue by shuvashish76** [celzero/rethink-app#602]
1 time crash.

**Crash logs**
```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.celzero.bravedns, PID: 23315
java.lang.NullPointerException: client not set
	at java.util.Objects.requireNonNull(Objects.java:228)
	at okhttp3.dnsoverhttps.DnsOverHttps$Builder.build(DnsOverHttps.kt:260)
	at com.celzero.bravedns.customdownloader.RetrofitManager$Companion.customDns(RetrofitManager.kt:75)
	at com.celzero.bravedns.customdownloader.RetrofitManager$Companion.okHttpClient(RetrofitManager.kt:46)
	at com.celzero.bravedns.download.AppDownloadManager.isDownloadRequired(AppDownloadManager.kt:95)
	at com.celzero.bravedns.download.AppDownloadManager$isDownloadRequired$1.onFailure(AppDownloadManager.kt:105)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Device details**
App version: **053j (21)**
Android: 8.1.0
Model: Lenovo TB-8704X

**Comment by ignoramous** [comment]
Hi, this has been fixed in v053k.

Dup #571?

**Comment by shuvashish76** [comment]
> This has been fixed in v053k

Thanks I'll reopen if I face such issue in v053k or later versions.
