### ISSUE TITLE
Crash v053k

### ISSUE THREAD

**Issue by trackerct** [celzero/rethink-app#606]
1666632306453,2022.10.24 10:25:06.453,INFO,-CleanerHomeFull,CleanerResultFullAds interstitialAD not null return
1666632339797,2022.10.24 10:25:39.797,INFO,-CleanerHomeFull,CleanerResultFullAds interstitialAD not null return
1666634647861,2022.10.24 11:04:07.861,INFO,-CleanerHomeFull,CleanerResultFullAds interstitialAD not null return
1666634672487,2022.10.24 11:04:32.487,INFO,-CleanerHomeFull,CleanerResultFullAds interstitialAD not null return
1666634683363,2022.10.24 11:04:43.363,INFO,-CleanerHomeFull,CleanerResultFullAds interstitialAD not null return

**Comment by ignoramous** [comment]
The stack trace / logs don't seem to be from Rethink. Can you actually share the crash logs?

**Comment by trackerct** [comment]
> The stack trace / logs don't seem to be from Rethink. Can you actually share the crash logs?

Where is the crash  logs file?

**Comment by ignoramous** [comment]
`adb logcat` if the crash was recent.

`adb bugreport` otherwise.

Refs:
- https://developer.android.com/studio/debug/bug-report
- https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/

(don't upload it here and instead send the output over email mz at celzero dot com)

**Comment by trackerct** [comment]
Thank you so much.

I sent you an email with crash logs. Did you receive my email?

**Comment by ignoramous** [comment]
Yes, I did. I'll take a look at the logs by tomorrow and get back to you (and follow up on this bug)! Thanks (:

**Comment by ignoramous** [comment]
Thanks. I see two "crashes":

---
```
11222:10-24 15:52:14.717 25525 25525 E AndroidRuntime: Process: com.celzero.bravedns, PID: 25525
11223:10-24 15:52:14.717 25525 25525 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
11224:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
11225:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1650)
11226:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
11227:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
11228:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:262)
11229:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.celzero.bravedns.ui.HomeScreenFragment.openBottomSheet(HomeScreenFragment.kt:654)
11230:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.celzero.bravedns.ui.HomeScreenFragment.access$openBottomSheet(HomeScreenFragment.kt:80)
11231:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:821)
11232:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:819)
11233:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.celzero.bravedns.util.Utilities$Companion$delay$1.invokeSuspend(Utilities.kt:459)
11234:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11235:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
11236:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
11237:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
11238:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
11239:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
11240:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
11241:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
11242:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11243:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11244:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11245:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6190)
11246:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11247:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
11248:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
11249:10-24 15:52:14.717 25525 25525 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1faa217, Dispatchers.Main.immediate]
```

...which *seem* similar to #459 (fixed in `v053i`). 

---

```
10-24 15:42:13.914  1223 24041 I ActivityManager: Killing 17693:com.celzero.bravedns/u0a752 (adj 700): kill background
```

Killed due to memory pressure. I can see a lot of other apps (including Google Play Services getting the boot, which points to the fact that the device may have been severely limited in memory at that point). Setting Rethink as `Always-on VPN` ([ref](https://support.google.com/work/android/answer/9213914?hl=en)) might help here.

---

```
10-24 15:44:17.716  1342  1342 D TileServices: Couldn't find tile for ComponentInfo{com.celzero.bravedns/com.celzero.bravedns.service.BraveTileService}
10-24 15:44:18.000 25525 25525 W System.err: java.lang.Exception: Toast callstack! strTip=Choose Mode.
10-24 15:44:18.001 25525 25525 W System.err: >--at android.widget.Toast.show(Toast.java:130)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.celzero.bravedns.util.Utilities$Companion.showToastUiCentered(Utilities.kt:275)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:822)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:819)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.celzero.bravedns.util.Utilities$Companion$delay$1.invokeSuspend(Utilities.kt:459)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
10-24 15:44:18.001 25525 25525 W System.err: >--at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
10-24 15:44:18.001 25525 25525 W System.err: >--at android.os.Handler.handleCallback(Handler.java:751)
10-24 15:44:18.001 25525 25525 W System.err: >--at android.os.Handler.dispatchMessage(Handler.java:95)
10-24 15:44:18.001 25525 25525 W System.err: >--at android.os.Looper.loop(Looper.java:154)
10-24 15:44:18.001 25525 25525 W System.err: >--at android.app.ActivityThread.main(ActivityThread.java:6190)
10-24 15:44:18.001 25525 25525 W System.err: >--at java.lang.reflect.Method.invoke(Native Method)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
10-24 15:44:18.001 25525 25525 W System.err: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

Not sure if this is a crash or just a stack-dump, but either way, we will take a look.

**Comment by trackerct** [comment]
Thanks for your work.

**Comment by trackerct** [comment]
@ignoramous Hi. 
I sent you an email with new crash logs. (v053l)

 Did you receive my email?

**Comment by ignoramous** [comment]
Hi there. Yes, I got the bug reports. The crashes seen are the same as before:

Do you know what set of steps you take when these crashes happen? Also, did these crashes show up in the latest `v053l` version?

<details>
<summary>OnSaveInstanceState and Toast erorrs</summary>

onSaveInstanceState1:
```
12-10 14:04:22.027 11064 11064 E AndroidRuntime: FATAL EXCEPTION: main          
12-10 14:04:22.027 11064 11064 E AndroidRuntime: Process: com.celzero.bravedns, PID: 11064
12-10 14:04:22.027 11064 11064 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1650)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at androidx.fragment.app.DialogFragment.show(DialogFragment.java:262)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment.openBottomSheet(HomeScreenFragment.kt:647)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment.access$openBottomSheet(HomeScreenFragment.kt:80)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:832)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:830)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.celzero.bravedns.util.Utilities$Companion$delay$1.invokeSuspend(Utilities.kt:505)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:751)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:154)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:6190)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
12-10 14:04:22.027 11064 11064 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d62bd43, Dispatchers.Main.immediate]
```

onSaveInstanceState2:
```
12-10 14:04:29.293 11122 11122 E AndroidRuntime: Process: com.celzero.bravedns, PID: 11122
12-10 14:04:29.293 11122 11122 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1610)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1650)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at androidx.fragment.app.DialogFragment.show(DialogFragment.java:262)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment.openBottomSheet(HomeScreenFragment.kt:647)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment.access$openBottomSheet(HomeScreenFragment.kt:80)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:832)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:830)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.celzero.bravedns.util.Utilities$Companion$delay$1.invokeSuspend(Utilities.kt:505)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:751)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:154)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:6190)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
12-10 14:04:29.293 11122 11122 E AndroidRuntime: >--Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@27ac41c, Dispatchers.Main.immediate]

```

```
12-10 14:07:44.626 12678 12706 I VpnLifecycle: Preferred engine name:IPv4,id: 2 
12-10 14:07:44.650  1194  1298 D ConnectivityService: Setting DNS servers for network 110 to [/10.111.222.3, /8.8.8.8, /8.8.4.4]
12-10 14:07:44.650  1194  1298 I chatty  : uid=1000(system) ConnectivitySer expire 2 lines
12-10 14:07:44.659  1194  1298 D ConnectivityService: Sending CONNECTED broadcast for type 17 NetworkAgentInfo [VPN () - 110] isDefaultNetwork=false
12-10 14:07:44.664  1194 12718 I chatty  : uid=1000 system_server expire 1 line 
12-10 14:07:44.684  1194  1298 D ConnectivityService: NetworkAgentInfo [WIFI () - 101] validation passed
12-10 14:07:44.684  1194  1298 D ConnectivityService: NetworkAgentInfo [VPN () - 110] validation passed
12-10 14:07:44.702 12678 12683 I art     : Do partial code cache collection, code=58KB, data=62KB
12-10 14:07:44.702 12678 12683 I art     : After code cache collection, code=58KB, data=62KB
12-10 14:07:44.702 12678 12683 I art     : Increasing code cache capacity to 256KB
12-10 14:07:44.716 12678 12731 I GoLog   : W dns64: err reg underlay(lookup ipv4only.arpa.: No address associated with hostname) / local(<nil>)
12-10 14:07:44.740  1194  1204 I chatty  : uid=1000(system) HeapTaskDaemon expire 1 line
12-10 14:07:45.216 12678 12678 W System.err: java.lang.Exception: Toast callstack! strTip=Choose Mode.
12-10 14:07:45.217 12678 12678 W System.err: >--at android.widget.Toast.show(Toast.java:130)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.celzero.bravedns.util.Utilities$Companion.showToastUiCentered(Utilities.kt:303)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:833)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.celzero.bravedns.ui.HomeScreenFragment$showStartDialog$1$1.invoke(HomeScreenFragment.kt:830)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.celzero.bravedns.util.Utilities$Companion$delay$1.invokeSuspend(Utilities.kt:505)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
12-10 14:07:45.217 12678 12678 W System.err: >--at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
12-10 14:07:45.217 12678 12678 W System.err: >--at android.os.Handler.handleCallback(Handler.java:751)
12-10 14:07:45.217 12678 12678 W System.err: >--at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 14:07:45.217 12678 12678 W System.err: >--at android.os.Looper.loop(Looper.java:154)
12-10 14:07:45.217 12678 12678 W System.err: >--at android.app.ActivityThread.main(ActivityThread.java:6190)
12-10 14:07:45.217 12678 12678 W System.err: >--at java.lang.reflect.Method.invoke(Native Method)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
12-10 14:07:45.217 12678 12678 W System.err: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
12-10 14:07:45.311 12678 12701 E EGL_adreno: tid 12701: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)

```
</details>

Though, this app-kill from `ldmnq.com` stands out (which might be specific to your ROM):

```
12-10 14:06:31.401 12245 12245 I appproc : exec app_process! cmdline: /system/bin com.android.commands.am.Am broadcast -a com.ldmnq.APP_KILL --es packageName com.celzero.bravedns --es pos pc
```

**Comment by ignoramous** [comment]
Most crash reports sent are dup of #663

Other crashes are from Kernel's LMK (low memory killer), which perhaps means Rethink is using far too much memory or there isn't enough memory on the Android Rethink is running on. Rethink is quite a memory hog if used with *on-device blocklists* (#572), so disabling it might result in some respite from the LMK. 

Pls feel free to re-open in case you think this bug was closed incorrectly.

Appreciate the detailed bug reports. Thanks! (:
