### ISSUE TITLE
Glide StrictMode Untagged Socket

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#633]
```
11-06 20:24:36.460 22891 22084 D DnsLogs : Glide - fetchFavIcon() -www.gstatic.com.
11-06 20:24:36.467 22891 17363 D StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage
11-06 20:24:36.467 22891 17363 D StrictMode: 	at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2251)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at libcore.io.IoBridge.socket(IoBridge.java:840)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.net.Socket.createImpl(Socket.java:514)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.net.Socket.getImpl(Socket.java:577)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.net.Socket.setSoTimeout(Socket.java:1203)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:93)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:421)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at java.lang.Thread.run(Thread.java:1012)
11-06 20:24:36.467 22891 17363 D StrictMode: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:380)

```

**Comment by hussainmohd-a** [comment]
More information is available here: https://github.com/square/okhttp/issues/3537

The issue happens when the fav icon is downloaded using glide lib(which internally uses okhttp), it seems there is no proper solution to this issue, but there is a work around ref: https://github.com/square/okhttp/issues/3537#issuecomment-400946758

The logs appears when the strict mode is enabled (debug version), glide issue ref: https://github.com/bumptech/glide/issues/3217
