### ISSUE TITLE
SecurityException: Package android does not belong to 10248 in ConnectivityManager.getNetworkCapabilities

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#653]
```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4881)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4918)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2309)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8577)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by java.lang.SecurityException: Package android does not belong to 10248
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2385)
  at android.os.Parcel.createException (Parcel.java:2369)
  at android.os.Parcel.readException (Parcel.java:2352)
  at android.os.Parcel.readException (Parcel.java:2294)
  at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities (IConnectivityManager.java:3347)
  at android.net.ConnectivityManager.getNetworkCapabilities (ConnectivityManager.java:1549)
  at com.celzero.bravedns.ui.HomeScreenFragment.isAnotherVpnActive (HomeScreenFragment.kt:1046)
  at com.celzero.bravedns.ui.HomeScreenFragment.syncDnsStatus (HomeScreenFragment.kt:993)
  at com.celzero.bravedns.ui.HomeScreenFragment.onResume (HomeScreenFragment.kt:692)
  at androidx.fragment.app.Fragment.performResume (Fragment.java:3180)
  at androidx.fragment.app.FragmentStateManager.resume (FragmentStateManager.java:606)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:285)
  at androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:113)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1433)
  at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2977)
  at androidx.fragment.app.FragmentManager.dispatchResume (FragmentManager.java:2909)
  at androidx.fragment.app.FragmentController.dispatchResume (FragmentController.java:285)
  at androidx.fragment.app.FragmentActivity.onResumeFragments (FragmentActivity.java:334)
  at androidx.fragment.app.FragmentActivity.onPostResume (FragmentActivity.java:323)
  at androidx.appcompat.app.AppCompatActivity.onPostResume (AppCompatActivity.java:242)
  at android.app.Activity.performResume (Activity.java:8378)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4871)
Caused by android.os.RemoteException: Remote stack trace:
  at android.app.AppOpsManager.checkPackage (AppOpsManager.java:7783)
  at com.android.server.ConnectivityService.getNetworkCapabilities (ConnectivityService.java:2295)
  at android.net.IConnectivityManager$Stub.onTransact (IConnectivityManager.java:1357)
  at android.os.Binder.execTransactInternal (Binder.java:1190)
  at android.os.Binder.execTransact (Binder.java:1159)
```

related: #626

**Comment by hussainmohd-a** [comment]
Not an issue. This exception will show up in a development environment where Android throws this error when the IDE tries to reinstall the app.

**Comment by ignoramous** [comment]
Happens on `v055u`:

```hs
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.celzero.bravedns/com.celzero.bravedns.ui.HomeScreenActivity}: java.lang.SecurityException: Package android does not belong to 10138
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

via:
```hs
Caused by java.lang.SecurityException: Package android does not belong to 10138
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1385)
       at com.celzero.bravedns.ui.fragment.HomeScreenFragment.isAnotherVpnActive(HomeScreenFragment.kt:1841)
       at com.celzero.bravedns.ui.fragment.HomeScreenFragment.syncDnsStatus(HomeScreenFragment.kt:1742)
       at com.celzero.bravedns.ui.fragment.HomeScreenFragment.onResume(HomeScreenFragment.kt:1185)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3210)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:666)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:310)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3251)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3219)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:666)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:310)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3251)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:333)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:322)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:232)
       at android.app.Activity.performResume(Activity.java:8155)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

via:
```hs
Caused by android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
	at com.android.server.ConnectivityService.getNetworkCapabilities(ConnectivityService.java:1669)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:978)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)
```
