### ISSUE TITLE
IndexOutOfBounds in FirewallStatusSpinnerAdapter

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#722]
Happened when "Bypass IP Rules" was set with a wildcard entry `*.*:443`. 

```
12-20 14:35:40.576 31550 31550 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.celzero.bravedns.adapter.FirewallStatusSpinnerAdapter.getItem(FirewallStatusSpinnerAdapter.kt:36)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.celzero.bravedns.adapter.FirewallStatusSpinnerAdapter.getView(FirewallStatusSpinnerAdapter.kt:53)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.Spinner.makeView(Spinner.java:724)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.Spinner.layout(Spinner.java:672)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.Spinner.onLayout(Spinner.java:634)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1822)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:539)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.android.internal.policy.DecorView.onLayout(DecorView.java:867)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4119)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3495)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2416)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9478)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:996)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:383)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:865)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:938)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:233)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:344)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8248)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
12-20 14:35:40.576 31550 31550 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```

**Comment by hussainmohd-a** [comment]
This issue is seen in interim build. Not in production.
