### ISSUE TITLE
NullPointerException in SettingsFragment.initView v053m

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#741]
```
type: crash
osVersion: google/oriole/oriole:13/TQ1A.230105.002/2023011000:user/release-keys
package: com.celzero.bravedns:24
process: com.celzero.bravedns
processUptime: 2614 + 176 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Locale.getDisplayName()' on a null object reference
 at com.celzero.bravedns.ui.SettingsFragment.initView(SettingsFragment.kt:130)
 at com.celzero.bravedns.ui.SettingsFragment.onViewCreated(SettingsFragment.kt:90)
 at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
 at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7878)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by ignoramous** [comment]
Android 13 only

https://github.com/celzero/rethink-app/blob/b10f667d1c4ae3beff4d34a78e2e151c004815fd/app/src/full/java/com/celzero/bravedns/ui/SettingsFragment.kt#L129-L130
