### ISSUE TITLE
Missing Levels for Packs cause OutOfBounds

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#756]
When levels information is missing, assume the highest level, aka `2`.

```
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: Work [ id=c45ac726-d7fe-4809-9049-9cb05791a4ce, tags={ com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator, CUSTOM_DOWNLOAD_WORKER_REMOTE } ] failed because it threw an exception/error
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:1012)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at java.util.ArrayList.get(ArrayList.java:437)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.service.RethinkBlocklistManager.readRemoteJson(RethinkBlocklistManager.kt:236)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.service.RethinkBlocklistManager.readJson(RethinkBlocklistManager.kt:110)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator.saveRemoteFile(RemoteBlocklistCoordinator.kt:132)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator.downloadRemoteBlocklist(RemoteBlocklistCoordinator.kt:114)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator.access$downloadRemoteBlocklist(RemoteBlocklistCoordinator.kt:40)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator$downloadRemoteBlocklist$1.invokeSuspend(Unknown Source:13)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
01-19 01:35:44.334 19495 28753 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
01-19 01:35:44.336 19495 28753 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=c45ac726-d7fe-4809-9049-9cb05791a4ce, tags={ com.celzero.bravedns.customdownloader.RemoteBlocklistCoordinator, CUSTOM_DOWNLOAD_WORKER_REMOTE } ]
```

Fix: https://github.com/celzero/rethink-app/blob/f6dd37cec669f5475958c449dbd2143e0db8a5ba/app/src/main/java/com/celzero/bravedns/service/RethinkBlocklistManager.kt#L236

(todo: need to check uses in other parts of the code?)

**Comment by hussainmohd-a** [comment]
Fix: if the level is empty, then set the level to 2

Commit: 872ab77ac00c2cd4833ff7c080e66b72ffacd5b6
