### ISSUE TITLE
[v054] NetworkLogsActivity ANRs

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#793]
Exceptions in Network / DNS Logs UI. Consistently reproducible by searching for a domain (with preferably 10000+ log entries) and then resetting the search term.

```
02-21 19:11:45.979 22329  4253 I Quality : stackInfo :----- pid 22329 at 2023-02-21 19:11:45.974 -----; Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=22329; 
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:421);  
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);  
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);  
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:3942);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4209); 
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010);
  at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028); 
  at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417);
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242);
  at android.view.Choreographer.doCallbacks(Choreographer.java:996);  
  at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:374); 
  at android.view.Choreographer.doFrame(Choreographer.java:865);  
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227);
  at android.os.Handler.handleCallback(Handler.java:938);
  at android.os.Handler.dispatchMessage(Handler.java:99);
  at android.os.Looper.loopOnce(Looper.java:233);
  at android.os.Looper.loop(Looper.java:344);
  at android.app.ActivityThread.main(ActivityThread.java:8248);
  at java.lang.reflect.Method.invoke(Native Method);
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589);
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071);
```
---
```
02-26 05:24:30.013 22389 31599 I Quality : stackInfo :----- pid 22389 at 2023-02-26 05:24:30.001 -----;Cmd line: com.celzero.bravedns;"main" prio=5 tid=2 RUNNABLE sysTid=22389;
  at androidx.recyclerview.widget.AdapterHelper.findPositionOffset(AdapterHelper.java:473);
  at androidx.recyclerview.widget.AdapterHelper.canFindInPreLayout(AdapterHelper.java:422);
  at androidx.recyclerview.widget.AdapterHelper.applyUpdate(AdapterHelper.java:194);
  at androidx.recyclerview.widget.AdapterHelper.preProcess(AdapterHelper.java:105);
  at androidx.recyclerview.widget.RecyclerView.processAdapterUpdatesAndSetAnimationFlags(RecyclerView.java:3942);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4209);
  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010);
  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578);
  at android.view.View.layout(View.java:23488);
  at android.view.ViewGroup.layout(ViewGroup.java:6575);
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103);
  at android.view.View.layout(View.java:23488);
  at android.view.ViewGroup.layout(ViewGroup.java:6575);
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841);
  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1822);
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1584);
  at android.view.View.layout(View.java:23488);
  at android.view.ViewGroup.layout(ViewGroup.java:6575);  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332);
  at android.widget.FrameLayout.onLayout(FrameLayout.java:270);
  at android.view.View.layout(View.java:23488);  at android.view.ViewGroup.layout(ViewGroup.java:6575);
  at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878);
  at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689);
  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395);
  at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124);  at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969);
  at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071);
  at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531);
```

**Comment by ignoramous** [comment]
Happens on tip, still:

```
04-09 17:15:38.526  1794 21461 E ActivityManager: ANR in com.celzero.bravedns (com.celzero.bravedns/.ui.NetworkLogsActivity)
04-09 17:15:38.526  1794 21461 E ActivityManager: PID: 7030                     
04-09 17:15:38.526  1794 21461 E ActivityManager: Reason: Input dispatching timed out (4d15c13 com.celzero.bravedns/com.celzero.bravedns.ui.NetworkLogsActivity (server) is not responding. Waited 5000ms for MotionEvent)
04-09 17:15:38.526  1794 21461 E ActivityManager: Parent: com.celzero.bravedns/.ui.NetworkLogsActivity
04-09 17:15:38.526  1794 21461 E ActivityManager: Frozen: false                 
04-09 17:15:38.526  1794 21461 E ActivityManager: Load: 23.26 / 23.14 / 23.64   
04-09 17:15:38.526  1794 21461 E ActivityManager: ----- Output from /proc/pressure/memory -----
04-09 17:15:38.526  1794 21461 E ActivityManager: some avg10=2.25 avg60=1.13 avg300=1.12 total=1079361861
04-09 17:15:38.526  1794 21461 E ActivityManager: full avg10=0.51 avg60=0.31 avg300=0.32 total=376009173
04-09 17:15:38.526  1794 21461 E ActivityManager: ----- End output from /proc/pressure/memory -----

...

04-09 17:15:38.526  1794 21461 E ActivityManager: CPU usage from 116ms to 564ms later (2023-04-09 17:15:35.044 to 2023-04-09 17:15:35.491):
04-09 17:15:38.526  1794 21461 E ActivityManager:   134% 20152/org.mozilla.firefox: 134% user + 0% kernel / faults: 1338 minor
04-09 17:15:38.526  1794 21461 E ActivityManager:     99% 20297/DefaultDispatch: 99% user + 0% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:     34% 20166/HeapTaskDaemon: 34% user + 0% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   100% 7030/com.celzero.bravedns: 100% user + 0% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:     100% 7030/elzero.bravedns: 100% user + 0% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   34% 1794/system_server: 9.4% user + 25% kernel / faults: 1009 minor
04-09 17:15:38.526  1794 21461 E ActivityManager:     34% 21461/AnrConsumer: 9.4% user + 25% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:     3.1% 4335/Binder:1794_E: 0% user + 3.1% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   6.6% 3035/com.whatsapp: 3.3% user + 3.3% kernel / faults: 1 minor
04-09 17:15:38.526  1794 21461 E ActivityManager:   2.2% 11/migration/0: 0% user + 2.2% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   2.2% 32/ksoftirqd/4: 0% user + 2.2% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   2.4% 351/irq/46-5-0034: 0% user + 2.4% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   3.2% 2211/hif_thread: 0% user + 3.2% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:   3.3% 3308/horae: 0% user + 3.3% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager:     3.3% 3344/st-fitting: 0% user + 3.3% kernel
04-09 17:15:38.526  1794 21461 E ActivityManager: 37% TOTAL: 31% user + 4.6% kernel + 1.1% softirq
04-09 17:15:38.532  1794 21461 D ActivityManager: Completed ANR of com.celzero.bravedns in 3605ms, latency 1ms
```

**Comment by ignoramous** [comment]
As a stop gap (may be a stop gap forever): The UI limits entries to just `35K` for now ([commit](https://github.com/celzero/rethink-app/commit/c03ca6a3d5a39f8ec04d65a88c0e95e45d6db6cb)). 100K+ rows per logs table are too much trouble for the current implementation, and fixes to handle that many rows aren't that straight-forward or obvious.
