### ISSUE TITLE
On DNSCrypt errors, Preferred and BlockFree transports go missing

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#810]
If DNSCrypt cert fetch fails, there's no transport left to connect to:

```
03-07 19:59:01.182  5839 12657 I GoLog   : I no certificate, ignoring server: [Preferred] relay: [<nil>] proto: [udp]
03-07 19:59:01.182  5839 12657 I GoLog   : W [Preferred] TIMEOUT read udp 10.1.204.174:49725->139.59.200.116:443: i/o timeout
03-07 19:59:01.182  5839 12657 I GoLog   : E dnscrypt: refresh failed Preferred: read udp 10.1.204.174:49725->139.59.200.116:443: i/o timeout
03-07 19:59:01.183  5839 12657 E VpnLifecycle: connect-tunnel: dns crypt failure
03-07 19:59:01.183  5839 12657 E VpnLifecycle: go.Universe$proxyerror: dnscrypt: error refreshing cert
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at intra.Intra.newDNSCryptTransport(Native Method)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.createDNSCryptTransport(GoVpnAdapter.kt:200)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.addTransport(GoVpnAdapter.kt:140)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.connectTunnel(GoVpnAdapter.kt:112)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.start(GoVpnAdapter.kt:72)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.restartVpn(BraveVPNService.kt:1550)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.access$restartVpn(BraveVPNService.kt:91)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invokeSuspend(BraveVPNService.kt:1256)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invoke(Unknown Source:8)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invoke(Unknown Source:2)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$io$1$1.invokeSuspend(BraveVPNService.kt:1940)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
```
03-07 19:58:55.962  5839 12703 D VpnLifecycle: onQuery: rcvd query: ssl.google-analytics.com, suggested_id: 
03-07 19:58:55.962  5839 12709 I GoLog   : W t.udp.dns: query failed missing transport
03-07 19:58:55.962  5839 12709 I GoLog   : D t.udp.egress: dns-override for dstaddr(10.111.222.3:53) <- src(l:10.111.222.1:57629 r:10.111.222.3:53)
03-07 19:58:55.962  5839 12709 I GoLog   : D ns.udp.forwarder: DONE err(EOF)
```
```
03-07 19:59:01.182  5839 12657 I GoLog   : I no certificate, ignoring server: [Preferred] relay: [<nil>] proto: [udp]
03-07 19:59:01.182  5839 12657 I GoLog   : W [Preferred] TIMEOUT read udp 10.1.204.174:49725->139.59.200.116:443: i/o timeout
03-07 19:59:01.182  5839 12657 I GoLog   : E dnscrypt: refresh failed Preferred: read udp 10.1.204.174:49725->139.59.200.116:443: i/o timeout
03-07 19:59:01.183  5839 12657 E VpnLifecycle: connect-tunnel: dns crypt failure
03-07 19:59:01.183  5839 12657 E VpnLifecycle: go.Universe$proxyerror: dnscrypt: error refreshing cert
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at intra.Intra.newDNSCryptTransport(Native Method)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.createDNSCryptTransport(GoVpnAdapter.kt:200)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.addTransport(GoVpnAdapter.kt:140)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.connectTunnel(GoVpnAdapter.kt:112)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.net.go.GoVpnAdapter.start(GoVpnAdapter.kt:72)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.restartVpn(BraveVPNService.kt:1550)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService.access$restartVpn(BraveVPNService.kt:91)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invokeSuspend(BraveVPNService.kt:1256)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invoke(Unknown Source:8)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$3.invoke(Unknown Source:2)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at com.celzero.bravedns.service.BraveVPNService$io$1$1.invokeSuspend(BraveVPNService.kt:1940)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
03-07 19:59:01.183  5839 12657 E VpnLifecycle: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
```
03-07 19:59:01.187  5839 12657 I GoLog   : I [BlockFree] Fetching DNSCrypt certificate for [2.dnscrypt-cert.dnscrypt.eu.] over [udp] at [139.59.200.116:443]
```
```
03-07 19:59:21.193  5839 12657 E VpnLifecycle: blockfree transport is null for dns type: DNSCRYPT
03-07 19:59:21.193  5839 12657 E VpnLifecycle: transport is null for dns type: DNSCRYPT
03-07 19:59:21.193  5839 12657 I GoLog   : I alg: translate? true
03-07 19:59:21.193  5839 12657 D VpnLifecycle: init bravedns mode
```
```
03-07 19:59:21.219  5839 12657 D VpnLifecycle: init remote bravedns mode
03-07 19:59:21.240  5839 12657 I VpnLifecycle: remote-bravedns enabled
03-07 19:59:53.607  5839 12709 D VpnLifecycle: onQuery: rcvd query: telephonyspamprotect-pa.googleapis.com, suggested_id: 
03-07 19:59:53.608  5839 12709 I GoLog   : W t.udp.dns: query failed missing transport
03-07 19:59:53.608  5839 12709 I GoLog   : D t.udp.egress: dns-override for dstaddr(10.111.222.3:53) <- src(l:10.111.222.1:55762 r:10.111.222.3:53)
03-07 19:59:53.608  5839 12709 I GoLog   : D ns.udp.forwarder: DONE err(EOF)
```

**Comment by hussainmohd-a** [comment]
This is the expected behavior. Rather than falling back to the `default DNS`, the status of DNS (_failing_) will now be displayed on both the home screen and the **dnscrypt list UI**. Previously, it was always shown as connected, but now it will be based on the transport response.

Closing this issues as the updating the status in UI is tracked here: https://github.com/celzero/rethink-app/issues/815.
