### ISSUE TITLE
security exception in local blocklist view activity

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#826]
User reported crash in v054a:

```
Process: com.celzero.bravedns, PID: 7905
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://raw.githubusercontent.com/... cmp=id.dana/.home.HomeTabActivity mCallingUid=11013 } from ProcessRecord{a2e1b04 7905:com.celzero.bravedns/u0a1013} (pid=7905, uid=11013) not exported from uid 10785
        at android.os.Parcel.createException(Parcel.java:2087)
        at android.os.Parcel.readException(Parcel.java:2055)
        at android.os.Parcel.readException(Parcel.java:2003)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3872)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
        at android.app.Activity.startActivityForResult(Activity.java:5320)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
        at android.app.Activity.startActivityForResult(Activity.java:5278)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
        at android.app.Activity.startActivity(Activity.java:5649)
        at android.app.Activity.startActivity(Activity.java:5617)
        at com.celzero.bravedns.adapter.LocalAdvancedViewAdapter$RethinkLocalFileTagViewHolder.update$lambda$2(LocalAdvancedViewAdapter.kt:96)
        at com.celzero.bravedns.adapter.LocalAdvancedViewAdapter$RethinkLocalFileTagViewHolder.$r8$lambda$L62swhS4v86QZzFqUfdbrDJ8Nvw(Unknown Source:0)
        at com.celzero.bravedns.adapter.LocalAdvancedViewAdapter$RethinkLocalFileTagViewHolder$$ExternalSyntheticLambda2.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7394)
        at android.widget.CompoundButton.performClick(CompoundButton.java:142)
        at android.view.View.performClickInternal(View.java:7348)
        at android.view.View.access$3900(View.java:827)
        at android.view.View$PerformClick.run(View.java:28293)
        at android.os.Handler.handleCallback(Handler.java:899)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7853)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1222)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:960)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:634)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1761)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:565)
```

**Comment by hussainmohd-a** [comment]
Fixed: https://github.com/celzero/rethink-app/pull/822/commits/198fe1863c9f142890003d96bbcc82b08548de36
