### ISSUE TITLE
v054b: NetworkOnMainThreadException at ConnectionTracer.getUidQ:74

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#853]
```
04-07 02:24:29.933 31794 31794 F DEBUG   : Cmdline: com.celzero.bravedns        
04-07 02:24:29.933 31794 31794 F DEBUG   : pid: 13423, tid: 8362, name: Thread-221  >>> com.celzero.bravedns <<<
04-07 02:24:29.933 31794 31794 F DEBUG   : uid: 10458                           
04-07 02:24:29.933 31794 31794 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
04-07 02:24:29.933 31794 31794 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallStaticVoidMethod called with pending exception android.os.NetworkOnMainThreadException:
04-07 02:24:29.933 31794 31794 F DEBUG   :   at java.lang.Exception android.os.Parcel.createExceptionOrNull(int, java.lang.String) (Parcel.java:2482)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at java.lang.Exception android.os.Parcel.createException(int, java.lang.String) (Parcel.java:2456)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at void android.os.Parcel.readException(int, java.lang.String) (Parcel.java:2439)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at void android.os.Parcel.readException() (Parcel.java:2381)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at int android.net.IConnectivityManager$Stub$Proxy.getConnectionOwnerUid(android.net.connectivity.android.net.ConnectionInfo) (IConnectivityManager.java:2738)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at int android.net.ConnectivityManager.getConnectionOwnerUid(int, java.net.InetSocketAddress, java.net.InetSocketAddress) (ConnectivityManager.java:5392)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at int com.celzero.bravedns.net.manager.ConnectionTracer.getUidQ(int, java.lang.String, int, java.lang.String, int) (ConnectionTracer.kt:74)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at int com.celzero.bravedns.service.BraveVPNService.getUid(long, int, java.lang.String, int, java.lang.String, int) (BraveVPNService.kt:275)
04-07 02:24:29.933 31794 31794 F DEBUG   :   at java.lang.String com.celzero.bravedns.service.BraveVPNService.flow(int, long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (BraveVPNService.kt:2083)
04-07 02:24:29.933 31794 31794 F DEBUG   : Caused by: android.os.RemoteException: Remote stack trace:
04-07 02:24:29.933 31794 31794 F DEBUG   : >at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1668)
04-07 02:24:29.933 31794 31794 F DEBUG   : >at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:168)
04-07 02:24:29.933 31794 31794 F DEBUG   : >at android.system.Os.connect(Os.java:139)
04-07 02:24:29.933 31794 31794 F DEBUG   : >at android.net.connectivity.com.android.net.module.util.netlink.NetlinkSocket.connectToKernel(Unknown Source:5)
04-07 02:24:29.933 31794 31794 F DEBUG   : >at android.net.connectivity.com.android.net.module.util.netlink.InetDiagMessage.getConnectionOwnerUid(Unknown Source:9)
04-07 02:24:29.933 31794 31794 F DEBUG   :                                      
04-07 02:24:29.933 31794 31794 F DEBUG   : (Throwable with no stack trace)      
```

Code: 
https://github.com/celzero/rethink-app/blob/53d2ed764d013a7589cd8e759a75c7458ef0fc39/app/src/main/java/com/celzero/bravedns/net/manager/ConnectionTracer.kt#L74

Probably, InetAddress aren't IP addresses?

**Comment by hussainmohd-a** [comment]
Closing the issue as it occurred in dev builds and has now been resolved in v054c.
