### ISSUE TITLE
ConnectionMonitor: StrictMode violation for untagged sockets

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#861]
```
04-15 02:50:10.287 15085  9644 D StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag
() to track all network usage
04-15 02:50:10.287 15085  9644 D StrictMode:    at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2251)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
04-15 02:50:10.287 15085  9644 D StrictMode:    at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
04-15 02:50:10.287 15085  9644 D StrictMode:    at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
04-15 02:50:10.287 15085  9644 D StrictMode:    at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
04-15 02:50:10.287 15085  9644 D StrictMode:    at libcore.io.IoBridge.socket(IoBridge.java:840)
04-15 02:50:10.287 15085  9644 D StrictMode:    at java.net.Inet6AddressImpl.tcpEcho(Inet6AddressImpl.java:221)
04-15 02:50:10.287 15085  9644 D StrictMode:    at java.net.Inet6AddressImpl.isReachable(Inet6AddressImpl.java:213)
04-15 02:50:10.287 15085  9644 D StrictMode:    at java.net.InetAddress.isReachable(InetAddress.java:525)
04-15 02:50:10.287 15085  9644 D StrictMode:    at java.net.InetAddress.isReachable(InetAddress.java:480)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.isReachable(ConnectionMonitor.kt:470)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.access$isReachable(ConnectionMonitor.kt:190)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler$checkIpv4Reachability$1$1$1$1.invokeSuspend(ConnectionMonitor.
kt:437)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
04-15 02:50:10.287 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.checkIpv4Reachability(ConnectionMonitor.kt:423)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.processLinkPropertyChange(ConnectionMonitor.kt:338)
04-15 02:50:10.287 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.handleMessage(ConnectionMonitor.kt:224)
```

```
04-15 02:50:12.574 15085  9644 D StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage
04-15 02:50:12.574 15085  9644 D StrictMode:    at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2251)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
04-15 02:50:12.574 15085  9644 D StrictMode:    at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
04-15 02:50:12.574 15085  9644 D StrictMode:    at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
04-15 02:50:12.574 15085  9644 D StrictMode:    at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
04-15 02:50:12.574 15085  9644 D StrictMode:    at libcore.io.IoBridge.socket(IoBridge.java:840)
04-15 02:50:12.574 15085  9644 D StrictMode:    at java.net.Inet6AddressImpl.icmpEcho(Inet6AddressImpl.java:249)
04-15 02:50:12.574 15085  9644 D StrictMode:    at java.net.Inet6AddressImpl.isReachable(Inet6AddressImpl.java:208)
04-15 02:50:12.574 15085  9644 D StrictMode:    at java.net.InetAddress.isReachable(InetAddress.java:525)
04-15 02:50:12.574 15085  9644 D StrictMode:    at java.net.InetAddress.isReachable(InetAddress.java:480)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.isReachable(ConnectionMonitor.kt:470)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.access$isReachable(ConnectionMonitor.kt:190)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler$checkIpv6Reachability$1$1$1$3.invokeSuspend(ConnectionMonitor.kt:460)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
04-15 02:50:12.574 15085  9644 D StrictMode:    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.checkIpv6Reachability(ConnectionMonitor.kt:445)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.processLinkPropertyChange(ConnectionMonitor.kt:334)
04-15 02:50:12.574 15085  9644 D StrictMode:    at com.celzero.bravedns.service.ConnectionMonitor$NetworkRequestHandler.handleMessage(ConnectionMonitor.kt:224)
04-15 02:50:12.574 15085  9644 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:106)
04-15 02:50:12.574 15085  9644 D StrictMode:    at android.os.Looper.loopOnce(Looper.java:233)
04-15 02:50:12.574 15085  9644 D StrictMode:    at android.os.Looper.loop(Looper.java:344)
04-15 02:50:12.574 15085  9644 D StrictMode:    at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by ignoramous** [comment]
Fixed in `v054c`:

https://github.com/celzero/rethink-app/blame/66f29707f1cf196b70809e13b35624586135c0a6/app/src/main/java/com/celzero/bravedns/service/ConnectionMonitor.kt#L524
