### ISSUE TITLE
ANR: startVpn-onNetworkConnected holds on to a lock and then UI thread gets in on the act

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#90]
In what looks like a case of `makeDohTransport` taking too long which then blocks all access to the sync methods in `VpnController` / `GoVpnAdapter` one of which is used by `QueryTracker#recordTransaction` which is called per DNS request. This is clearly undesirable even though it doesn't happen often.

Two of the many `QueryTracker#recordTransaction` threads blocked by thread 62.
```
"Thread-14" prio=5 tid=3 Blocked                                                
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x12cc1280 self=0x7c85957800    
  | sysTid=4929 nice=0 cgrp=default sched=0/0 handle=0x7bf0232d50               
  | state=S schedstat=( 26198170565 14597836902 129444 ) utm=1218 stm=1401 core=2 HZ=100
  | stack=0x7bf013c000-0x7bf013e000 stackSize=991KB                             
  | held mutexes=                                                               
  at com.celzero.bravedns.service.VpnController.getTracker(VpnController.kt:-1) 
  - waiting to lock <0x0e8607a2> (a com.celzero.bravedns.service.VpnController) held by thread 62
  at com.celzero.bravedns.service.BraveVPNService.getTracker(BraveVPNService.kt:412)
  at com.celzero.bravedns.service.BraveVPNService.recordTransaction(BraveVPNService.kt:385)
  at com.celzero.bravedns.net.go.GoIntraListener.onResponse(GoIntraListener.java:156)
                                                                                
"Thread-15" prio=5 tid=4 Blocked                                                
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x12cc12f8 self=0x7b8c993000    
  | sysTid=4892 nice=0 cgrp=default sched=0/0 handle=0x7b8704ed50               
  | state=S schedstat=( 20201963840 10754368582 93158 ) utm=764 stm=1256 core=0 HZ=100
  | stack=0x7b86f58000-0x7b86f5a000 stackSize=991KB                             
  | held mutexes=                                                               
  at com.celzero.bravedns.service.VpnController.getTracker(VpnController.kt:-1) 
  - waiting to lock <0x0e8607a2> (a com.celzero.bravedns.service.VpnController) held by thread 62
  at com.celzero.bravedns.service.BraveVPNService.getTracker(BraveVPNService.kt:412)
  at com.celzero.bravedns.service.BraveVPNService.recordTransaction(BraveVPNService.kt:385)
  at com.celzero.bravedns.net.go.GoIntraListener.onResponse(GoIntraListener.java:156)
```

UI thread blocked by thread 62.
```
"main" prio=5 tid=1 Blocked                                                     
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x72eefa78 self=0x7c85955c00    
  | sysTid=4842 nice=-10 cgrp=default sched=0/0 handle=0x7c86ec3ed0             
  | state=S schedstat=( 48486363045 6879802907 45797 ) utm=4195 stm=653 core=0 HZ=100
  | stack=0x7fe5b47000-0x7fe5b49000 stackSize=8192KB                            
  | held mutexes=                                                               
  at com.celzero.bravedns.service.VpnController.getState(VpnController.kt:-1)   
  - waiting to lock <0x0e8607a2> (a com.celzero.bravedns.service.VpnController) held by thread 62
  at com.celzero.bravedns.ui.HomeScreenFragment.startQueryListener(HomeScreenFragment.kt:404)
  at com.celzero.bravedns.ui.HomeScreenFragment.access$startQueryListener(HomeScreenFragment.kt:59)
  at com.celzero.bravedns.ui.HomeScreenFragment$initializeClickListeners$4.onClick(HomeScreenFragment.kt:243)
  at android.view.View.performClick(View.java:7201)                             
  at android.widget.CompoundButton.performClick(CompoundButton.java:142)        
  at android.view.View.performClickInternal(View.java:7170)                     
  at android.view.View.access$3500(View.java:806)                               
  at android.view.View$PerformClick.run(View.java:27562)                        
  at android.os.Handler.handleCallback(Handler.java:883)                        
  at android.os.Handler.dispatchMessage(Handler.java:100)                       
  at android.os.Looper.loop(Looper.java:214)                                    
  at android.app.ActivityThread.main(ActivityThread.java:7682)                  
  at java.lang.reflect.Method.invoke(Native method)                             
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)               
```

thread 62, holding on to the lock for its dear life.
```
"startVpn-onNetworkConnected" prio=5 tid=62 Native                              
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x1461e680 self=0x7b42971400    
  | sysTid=24750 nice=0 cgrp=default sched=0/0 handle=0x7b8ef74d50              
  | state=S schedstat=( 2182451 1284270 14 ) utm=0 stm=0 core=6 HZ=100          
  | stack=0x7b8ee72000-0x7b8ee74000 stackSize=1039KB                            
  | held mutexes=                                                               
  kernel: (couldn't read /proc/self/task/24750/stack)                           
  native: #00 pc 00000000002ae4dc  /data/app/com.celzero.bravedns-e1C2K2GeixFoXgZEdDCheg==/base.apk (offset c000) (???)
  at tun2socks.Tun2socks.newDoHTransport(Native method)                         
  at com.celzero.bravedns.net.go.GoVpnAdapter.makeDohTransport(GoVpnAdapter.java:205)
  at com.celzero.bravedns.net.go.GoVpnAdapter.connectTunnel(GoVpnAdapter.java:119)
  at com.celzero.bravedns.net.go.GoVpnAdapter.start(GoVpnAdapter.java:104)      
  - locked <0x0eb0cc33> (a com.celzero.bravedns.net.go.GoVpnAdapter)            
  at com.celzero.bravedns.service.BraveVPNService.startVpnAdapter(BraveVPNService.kt:586)
  - locked <0x0e8607a2> (a com.celzero.bravedns.service.VpnController)          
  at com.celzero.bravedns.service.BraveVPNService.startVpn(BraveVPNService.kt:573)
  - locked <0x0e8607a2> (a com.celzero.bravedns.service.VpnController)          
  at com.celzero.bravedns.service.BraveVPNService.access$startVpn(BraveVPNService.kt:62)
  at com.celzero.bravedns.service.BraveVPNService$onNetworkConnected$1.run(BraveVPNService.kt:544)
  at java.lang.Thread.run(Thread.java:919)        
```

**Comment by ignoramous** [comment]
With https://github.com/celzero/firestack/issues/2 `makeDohUrl` is now a cheaper operation. This has introduced other complications like the tunnel is without a DNS server connections but ends up with a state where the user cannot possibly ever connect to the internet, this is aggravated by the fact that, at times, only RethinkDNS isn't able to connec but all other apps are...making the user think RethinkDNS is dropping those connections. Before this change, `makeDohUrl` would have failed (since network connectivity wouldn't have existed) and the app would have refused to start the `tunnel` at all.
