### ISSUE TITLE
NullPointerException ConnectionTrackerFragment (line 136) setupRecyclerScrollListener.scrollListener.onScrolled

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#915]
Not sure what caused it:

```
05-20 06:49:09.119 13431 13431 E AndroidRuntime: FATAL EXCEPTION: main          
05-20 06:49:09.119 13431 13431 E AndroidRuntime: Process: com.celzero.bravedns, PID: 13431
05-20 06:49:09.119 13431 13431 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.celzero.bravedns.ui.ConnectionTrackerFragment$setupRecyclerScrollListener$scrollListener$1.onScrolled(ConnectionTrackerFragment.kt:136)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5347)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4405)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1822)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.layout(View.java:23488)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.layout(ViewGroup.java:6575)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:991)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.dispatchTouchEvent(View.java:14668)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2853)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:567)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1917)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.app.Activity.dispatchTouchEvent(Activity.java:4256)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:515)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.View.dispatchPointerEvent(View.java:14940)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6992)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6763)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6228)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6425)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6482)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9372)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9312)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9258)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9526)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:265)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:245)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9467)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9617)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.Choreographer.doCallbacks(Choreographer.java:996)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:366)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.Choreographer.doFrame(Choreographer.java:865)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.os.Handler.handleCallback(Handler.java:938)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.os.Looper.loopOnce(Looper.java:233)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.os.Looper.loop(Looper.java:344)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at android.app.ActivityThread.main(ActivityThread.java:8248)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at java.lang.reflect.Method.invoke(Native Method)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
05-20 06:49:09.119 13431 13431 E AndroidRuntime: >--at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```

**Comment by hussainmohd-a** [comment]
Not sure what caused this issue. It seems that the issue was triggered by the `getTag()` function invoked during recycler scrolling. I have handled the null reference where `getTag `is accessed. Closing it for now, but I will investigate further if the issue occurs again.

**Comment by ignoramous** [comment]
Commit?

**Comment by hussainmohd-a** [comment]
Commit: https://github.com/celzero/rethink-app/commit/3c1b9db25f07d288db8950214d6317067f90fe51, contains the null reference check along with other changes
